### ISSUE TITLE
PMMP seems to have blocked me from the repo so...

### ISSUE THREAD

**Issue by CortexPE** [CortexPE/TeaSpoon#103]
### PMMP seems to have blocked me from the repo <sup>(I can't star nor watch it but in other orgs I still can)</sup> so... just update me with the features they have implemented here...

# Why?
Because PMMP has blocked me, I can't get updates on what features they have implemented via email.

# Why did they block me?
I actually don't know. probably because a some people at PMMP hate me for some reason. 😕 

## Okay, what do you want us to do now?
Ok first of, **don't spam them to unblock me (in case you wanted to do that) *that'd only cause more drama*** 😂 
Just comment down below the commits they have pushed that implements a new feature 😄... that'd be great!

-----
<p align="center">👻 rip 👻</p>

**Comment by NycuRO** [comment]
1. dktapps blocked you with that reason: TeaSpoon He really hate plugins for pocketmine like as TeaSpoon. 2. TeaSpoon have succes and that's reason of shit dylan.
3. What's the problem if them blocked you? You can simple watch commits on github 👍

**Comment by CortexPE** [comment]
I'd probably just setup a discord bot to do that for me xD

*I'd usually just make technology work for me 😂*

**Comment by CortexPE** [comment]
![image](https://user-images.githubusercontent.com/17762324/34340826-c1b1dd5e-e950-11e7-8a2a-25ccfb598fe8.png)
heh.

I'm not violating GitHub rules amiright? 🤔 😂

**Comment by Thunder33345** [comment]
>dktapps blocked you with that reason: TeaSpoon He really hate plugins for pocketmine like as TeaSpoon. 2. TeaSpoon have succes and that's reason of shit dylan.
Please quote your source?
you cant just go everywhere and spread fake news
I personally doubt Dylan is such kind of person who will just shit over some personal opinion/dispute

**Comment by CortexPE** [comment]
https://twitter.com/dktapps/status/933630103535448064
https://twitter.com/dktapps/status/933630619053166593

not trying to start drama myself, but here's his opinions about TeaSpoon...

**Comment by NycuRO** [comment]
@CortexPE Good luck :3

**Comment by Thunder33345** [comment]
Again he disliked "TeaSpoon" not you personally
but i think you should try to respond these criticism and fix it

**Comment by CortexPE** [comment]
I will on later... Since I don't have contact to him directly, I'll just add my response to the Wiki (as a part of the FAQs section)... It won't be directly just for dylan but it should answer all the issues regarding why this 'huge plugin' was actually made and what is the intention of it.
