### ISSUE TITLE
Armour

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#109]
Could you make it for when u tap on a block with armour in your hand for it doesn't auto equip onto the player thanks

**Comment by CortexPE** [comment]
try testing it on vanilla minecraft...

**Comment by CortexPE** [comment]
and, pmmp also triggers air click when a block is clicked...

**Comment by BajanVlogs** [comment]
Its not vanilla
its pmmp could u make a hack for it
