### ISSUE TITLE
Enchants give errors

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#115]
28.12 17:22:16 [Server] Server thread/CRITICAL Could not execute task CortexPE\checkTask: Index invalid or out of range
28.12 17:22:16 [Server] Server thread/CRITICAL RuntimeException: "Index invalid or out of range" (EXCEPTION) in "src/pocketmine/item/enchantment/Enchantment" at line 110

**Comment by CortexPE** [comment]
update PiggyCE

**Comment by BajanVlogs** [comment]
I don't use PiggyCE

**Comment by BajanVlogs** [comment]
I use your enchants
