### ISSUE TITLE
Splash Potion stack up to 64 but drinkable potion work fine 

### ISSUE THREAD

**Issue by SpecialistNinja** [CortexPE/TeaSpoon#117]
## Issue Description

A short description about the issue

## Steps to Reproduce

1. ...
2. ...
3. ...

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by BajanVlogs** [comment]
So you mean that splash potions stack and don't work?

**Comment by SpecialistNinja** [comment]
No it just that pot are stack up, when in single players it dont stack

**Comment by BajanVlogs** [comment]
Ok have u tested it without any plugins

**Comment by SpecialistNinja** [comment]
Yes i alkready did
