### ISSUE TITLE
Implement FloatingText

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#122]
Add this in to fix issue #110 

As Slappers use FloatingText and when limit of the text is reached the server just closes adding this will fix that

https://github.com/pmmp/PocketMine-MP/pull/1393/commits/8adcd64a26716685f07766ad717cd2ed7a60074a

**Comment by CortexPE** [comment]
they just have to set the age to 0 in every tick. nothing more. nothing less.

**Comment by CortexPE** [comment]
nvm https://github.com/pmmp/PocketMine-MP/commit/8adcd64a26716685f07766ad717cd2ed7a60074a#diff-6c0d2bc4008bffc80d18e3528fcc5271R81
