### ISSUE TITLE
Plugin wont start ._.

### ISSUE THREAD

**Issue by LagHD** [CortexPE/TeaSpoon#130]
PocketMine-MP Crash Dump Sat Dec 30 00:41:38 PST 2017

Error: Class 'pocketmine\item\ChorusFruit' not found
File: TeaSpoon_dev-82.phar/src/CortexPE/item/ChorusFruit
Line: 43
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: TeaSpoon v1.0.0

Code:
[34] declare(strict_types = 1);
[35] 
[36] namespace CortexPE\item;
[37] 
[38] use CortexPE\Main;
[39] use pocketmine\entity\Living;
[40] use pocketmine\item\ChorusFruit as PMChorusFruit;
[41] use pocketmine\Player;
[42] 
[43] class ChorusFruit extends PMChorusFruit {
[44] 
[45] 	public function onConsume(Living $consumer){
[46] 		if($consumer instanceof Player){
[47] 			$session = Main::getInstance()->getSessionById($consumer->getId());
[48] 			if(floor(microtime(true) - $session->lastChorusFruitEat) < Main::$chorusFruitCooldown){
[49] 				return;
[50] 			}else{
[51] 				$session->lastChorusFruitEat = time();
[52] 				parent::onConsume($consumer);
[53] 			}

Backtrace:

PocketMine-MP version: 1.7dev #516 [Protocol 160; API 3.0.0-ALPHA10]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mcpe1.netherbox.com 2.6.32-042stab120.18 #1 SMP Fri Jan 13 10:32:04 MSK 2017 x86_64
PHP Version: 7.2.0RC3
Zend version: 3.2.0-dev
OS : Linux, linux

Loaded plugins:
WorldBorder 1 by CookieCode for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11
BasicHUD 1.0.6-3 by aliuly for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
XBL_PlayerList 1.1 by TheRealLinuzo for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
EnchantUI 0.0.1 by VCraft for API(s) 3.0.0-ALPHA10
Sizer 2.2.0 by CapricornOfLynx for API(s) 3.0.0-ALPHA10
Worlds 1.0.13 by  for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
PureEntitiesX 0.2.8-3.alpha10 by milk0417, RevivalPMMP for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
PlayerCorpse 1.0.0[S255] by Syams255 for API(s) 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 4.0.0
DevTools 1.12.8 by PocketMine Team for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
TeaSpoon 1.0.0 by CortexPE for API(s) 3.0.0-ALPHA9, 3.0.0-ALPHA10
PurePerms 1.4.1-3 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10
MagicWE2 5.3.3 by XenialDan for API(s) 3.0.0-ALPHA10

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVW41v28aS/1cWcnFNDiItSrJsq+cCqe28+p79rLOcS4GoMFbkUtqaXLJc0rZS5H+/mdldftlt
07QPxRVwbe7H7MzszG8+yPwyKGUqBvPgIJjOxpPx8dFwIIoiKwbzXwblLoepwfnd+c3N9c1gOEiF
1nyDY6cJ15p9nWfhvShTqcRqJUuRrlan26yo9NuikuXXTGUli7NKRbA3lgluvBV8mWeZuovEg3c0
9vMtL/Z1Ee6fZkUpnhbn+0hnv0UG9iZwwGA+nXwaDvKk2kjVIgTTYRYJ5HcyhfFIhAkvxCtdFjIs
71AGzU5Y8PobWDk5gBX4ewa/FQd5ch4K5s42QtDCQ7vwCH5Xur3kiktFS47tVFsJQpWy3K1Wl/JB
qg0um45eWPZMV4xrtrhqDdDW4IWti4TvREHTY8PjdAK/Q7qQNkXxVAoV9ciyX3DD1G5EbazKvFon
MmRxpcJSZopl6jRTukrFKyMF+yo0z8Vr2j2jXatSxq/qGSaVLrkKRRYzw6FZe2jXrsqvNBgPkj9h
qMH5fCPKC7vp1WvvW3hcmhXf7S6ihjLNwMBrusDpUU0Qjo+TLCtepTIsMjTjV2VRidfMY+4s71vQ
StkS/5yXr9l/WQa+CpuJ0yxLouxRGa6P60NWZSHKqqALPxjVw59EogUuPQhaS3/rWBCbWCQpDsat
XTlYqyrn80btjb5p8aQ5dgAeUBZgsoP5hx+Hg41QouAJ2j4aM6xbkKVcgaV4VwvY/CAK5AhmAv8Q
XA6G1pVMosH8IJiBN4HisjADCsFsNBzwXMLKiT/yR96by8X3b4IRbNiAD84Ho8/8DzYU/D6Ra9zj
H/s4UFnuLqWqnlga5iLwlSi3olhnT36YpWzsz/zJ2BtNx2AR62A88oMjthew5dWCvS0k+2+uWDBh
wWg+Gc9HU3a1/Ccbj4JD9nQ0u5tN4Yx8m8MJh/7YH92cTmDgI1g/SQMjnhEd1txl2jECA/SQ0EON
LRrV+T4rkui7rIhE0dJue7SjW3jiVQkXDps/DMCY7qU4RVT60Sr1g9Eqwkaj3Vn38bD7eNR9PO4+
Bj1aQYBnCcXXiQCxYw4GOgQwzBEDjLXoLC7P2gMpJyRt2F2tWhIapEP0zTgqcnG9vH1/fXN5BkOP
Yq0BwxBGQG/fcS3D79+dtTRVD3VNcOTPvElXWTyRVbLrK+rLNPKlGjA8rFbbKvo8qbdlmev5/j64
xrZaowXv80T8xFVUZEBrvwFszxrVPgCJ2E8BF0SxX2sHlPfDd5d3BjEvpS5bKuxNdBXZs7jbrbgR
PEGz/pi9rMu/Tludw1arLp+fbzXnWmO0hIMX5y2xO8NtocfWgVpiX4oNcncdX50uzhlkBOnfa0dt
3iEHAA0QUPxRUzJiGan2O/pAtalwy1X57qKts3qsrTCQqG8n/3ta8Lh8WUl/Qm5DFtn9/Otfyo8d
bDXP3Qsf9y/8lOeQ1WWFuo4vd+rpLxekR3+1Iq5Wq+RLr7LPMAhOEKv7UUU/Q8qgC5R/q2Hrqnjg
q9UjcWqjhP6cW15UhTjHnFgK/UM7T+mMd6127B95E58nUBoEvftPZXI/mgYo9o14kA88WVxBnvMF
gIep4mcKX5iT8jTNV6scGBeWcUjGW2I06ljevrm5fbf4PdtoSbDf1QcqjhAVqo5ci7be2sN9ixl9
WI4PDn7sqmy546mG4ZeV9BlJxpRw90stxx3/J+DQkBgfoFrOxMMtpOpt96mHehESzKiriSY3/jeF
ij9gU47p1arF/h8zn0ac/ZoGaKiuixsNtUrlnsH081ZT4/6b/albSn+e3G6P/7T76HBlIYpU9zDF
jHXlnPpBP+mcTd++HY3Yf7BFkf0kQihEY6mgcP9704c7w5aBFZKk9ecXOA7ttelnQwe0d8U3Mnx/
Pm4prx5q6+7An/g9zf0gFOQiZ1x9Vuz9A1bxRIQjrtAsDC/PMeMlExl8wtKNFyAH5NbuFFGAGD7U
t7koCJ3ng71F/cSg1I7lhmFTaqX2bivBzkTIxjMWHM3H03kwZYvlLVWYK2VoeTI/CUZTfzLzjw78
ZjgHyzwJjoPJeKVS/gT5PiK0PpnNZiuViAeReKjiE4qdsCQro5Pxd+PblXrcggBeAknzSRbHK8WV
yioVCkvC4+FWwv4Uwo02K3TOH5WHRbugVs3JCHYlSfboxYncbIGOcou4kimYXmskzdbmcQPspFDt
4e44K+DAeoRO2fIigpTFPuUPOe2KZBzLsErK3UkANKjzUGaFp0VZSrXRJ05aLUR04kEJPzk6Do4O
jt04duJOzs7fvnl3CcIbE/F+rkSxI/p2oAhBLDoY//JzrjVoLjr5T/oPxK3KzNP8QdCmBykevUia
LtLJ0Uo9rbMnD8315Fo53ZhOwwna4kplCpuJHklrRpx2FJZm2g5uRZLQjdEztg7qis7fpQlaE3WR
WEiGVIEusLeF9sRAp6zTh1kVYGMMyiYtmFMX44VgwBfLFJhjueUlC9EASrYWTKowqSIRwR/smSUb
assshb0xkuhT1TwWQ5ah0BqJsnUh+D3bZVVhqTEZM9CAjCWdAZddgEFBBUyk/yUea4L7kYg5XLpm
j5n6umQ8zwUvGN5CCiKHoOEdcllupTbSP26FYlW+KXgEBHwkiT+O4Bwf2N7tFtIoL4FB4CbhalPx
jWDYyCX1Wd/SEp6TDE6RH0nBZvPpVoRWnu5WuAEHg0L5j/Je5iKS3M+KzT4+7WOFepfFdxfL67vZ
5Ngb3+E+UmlNas5WAGCb1cAc9n5L5sPKDLhSEQOJGfaWUdtlwZVOeAlapGnSLfELvMBfoqQrjiDR
CwWDEi1K6NJTIm18rzmWQgXN6G1VYjfSsw13ZGlpqIdJpkXkmHuDBs4QQrBPa1sN7EFy9j/oWLSI
XMy1IeaM7Js2L7ewl6MF6wz4smeZC+SWGKs0mCcAOBgIyflmcQErIRxERmvNlPeA7Twt2keck1M7
WiA/Q2BhYMxgK8jyeseshdEGCwL1fFspe+8lqB78d8d4FLFCaGOXyC5Y4j2wxaFOIbxkYI1rgbqB
axA/VzzBC9rIB1gLKTfA/St7LGD8ayJvzgQAEojoHtzwZiOKOcyb0/9VpWvQP7jcG71T4S3X9+AT
xT04mW9WvIOLIet14uK6bZEBqoOpwHo9ZIQpzKInGPQQFJKCBk1rHBUEgQ3H0kqBd+ESS31JxgRy
gQsW2ROgeylAFSAWOYKq2UMNO5YuYvRkXIQeO2Sy/Bp0WBa0LxIYRshCe7vZK5ACXzyMjW5IEs9K
Oydazq8xcBQ769X/SLI1qBpDPDMTYJupLBEhUrHh610JrLGlYWlETEiNV+5QAeR7lMQiqZ8hfhtK
7kY0aSmWYEYAbRBZFBGLAU/cmcYkQKyKDHqTgUQZOg/qj07aEKMeMTdnIycM2yNMLwGcePT/QAxM
nX5HCAzmf1IIXWY58WEBrubL0tMM3A4DNeBSzRWe61gLRuNpwx25z3uyJcuk/vqvYDMsuN4SX+hr
LKwKfK8CLiKeRFgRQGaGb2PIGATr1eIphLRFN2JZp7++PZ+z2+8vluzy4uriFuBvcXlxvmSL8xsG
Ofg/z2+GDBax22tYdc7ef399ec4WN9en58ul/8x3fkMrkJvLjAI+YplGOUMKc1YpNV4FcA0A2ZHx
TFrjAZYIh1Q2RGYKJAacAwtDyX/NAI3hQSaaUPRExDTLDHVDBfCrwUMH7uaca4RjzCZok/98A5qH
LQfgFnMRYtJh9Ixcm2s2e2tRwOJErhuRJyMrs379K2xZDUwaDWx4sQav8cIsSUyybDDqRU2TGyJL
dhezuwAFU64qSnLa3EAaWIFZvh46dH1ml9YwTbSKY6BlZE4b1/TZtUksjA9A0M+qJKp5kQDHj4o1
/BuXZzmxD7LORqNGXLb3lqDkWcghQzI0auniIktd7DK77Qqvbay9qwaJ7I0+t5MXzKtvKEuXoeLl
FXAcWqW17ahKc5MduYzRzng44+7tDFfZHSQBMevkwBfoj5C04+9nioYwCEESjngAg9O6EggZ5RZu
b+OyW8Q0PK1ha+gu1IRdm8Aa9mjpb2kLK8FwW6l77dg/5TmOyrRKIXdRUNYyV7jgnTJT9BlGGvWi
+1iNkgM9NzfI8HPLFB3oYeJdQZSetq7uLDOTfQM3r/vdCWaxcylDzS7siUdpjBdChSpqAc+AH0pH
ITtDLQKLJtsxhHKOFREze4yYjYiwzerVCOUOx8WtfBK0mGD5Yen+Nqnfs0n8gdIQr69VlIAXJiaL
W/MSCnBMq4lzSN7Aomw4ItgzpZedNTFoLep8zgbDvfaVuTmE3WJXIvUh84LWbZqbpKO90rED0H4w
c7jeZItUVmOaFhkdYHlCOTXuhkHLmc++lxsEmhOo+QAjThfvhrAXuFiDyz3KCByBMgyLrfUBHh0w
Z4d1etukvppU1FrsszcRgNiWJ/E+lLQmI48EGLU9DI5l2MVBe2s5ZytGtqh18v7zJ8Q8TOt5MjSQ
ioe/lwpqJBAPcEkQzmHG+m6hFi7fbSpUTOlx0yPEXyJa5Sr37EC3zsCfSKyrjTOKzMYvhhlOQS5j
MwpM3zEA4JcGfj2r0U4oJ8+3uS+VRHYCK6db45zmPS8Uxs/WbizhbcRESpYIoBFEcxSsWZlysPgU
rrlEpRaVwi9MEExAsJSABSi74GsOBHmVJ2PPjrZrNQDJb1mANYJN+7A8JE240lCbSl+4ktGUzcZI
gnbBp9k+IFtZgc/sb0JnV8BSpNs3i/8zsDd3hX0GBSRasyu5hSsgCRwjXnKm+UONw9gIcu0ynGzJ
w0EbACOCl07XIKDpxrrcnKogMDnKgXQOCSDlRCoLE5kz2gvmdQVaDjnaVpo9uOoSY4hVqWkyuTlz
pO6AVnMwXhD4XZKBc1BXRhshsW61QhoDwEYQUUJRWyx0ohe2gIgWgqAMt/XOHRilaRglZCEJsVYb
geGYvtgiJrq46Lp4vX6NcIU6I+sqTc+KFlvwq7RtHoRAtLT4Zzd5ZtOc5WAFDzKxpUDHSfEdNoQm
S5IAhLJB0BACRomgMR7ZrA1DpkkKzW1jWxBnbCbYmEFnwuXerqhfCpuXrbkWrSNfBYCWL5w1ZGP8
lvClCVGG/muL3lq0ebGucYvUsXvk7llA/DJnogUa1VHXrmnnRS6mYgpi64nkke+0oW8p9dDLxE4b
DRoUs+q1RZzC+0j6mcjQreo0Vl9sQ9oOw5s0A9yhzgGlOxiFKOA5KVFHyKxpsoCf4oPNTtjeDSUr
re1kVUqYjtpaGHJrEWPkok4tpRZb5y0GBaiD+yzvMXrA4xo9XPEnxvssg1AhRezmSvrcjn6FXV7g
563ULiOEAqbr7dYEDFcTA5bYpfeqHLBKdKAwxLzGXCp28zq4fEYHWkdH90btGpAHa4UgmDIrJHPd
IpdG0aauCtieB0a8xzZQLuuuqpq2VKMt/7m6bBB45JKK6p8rYSIT3JalYH2fZjwtP4ITHH0hxTzL
q6SmaJ8wOXlGHH/ILb3cBRR0fgwRc9YulggSTJtv7mAAO5PUPzDjJr2xdgEstZqT7ZiJPuZhB7k/
VqNnbxyCuVRx1r55QE3PNK2btdsMTYAY8vGzA1/W/TauMrVLsfTFCIuN31C3pMCq3i5gzQKShoIn
32wKsbGtx7rFixUBflZ6/0xU4hPg4/rseg66sXmDqYgIsB6FKas4OO0jHamJ/ZYcNOi3XqBA1t25
C+MP9s6eaxku26yYt3IYm4K04yyNZx1FQtWl0IoijClZjlFwyOjLkiEMgz7wXUPZJN6QDMSigFLL
QxxUmNjgsjpBqtAYQNYWPWZfl7YSpwqKDV0aKHVwZekZUzAL3BnPb96I2796SB5aEdnmSkgbN7n8
F28awRvPpSTU7nL9cr91jJ3qn+NU+zs5mQ0k5sqN27R6bO6tQilLp1zXTdvaUUItLHlt5WRBC1v7
UKZGVDXIuKYElSjI06RHncSWCFqwbiczPJEQjZ3Ozp84JkPuETNc4NVe4NzdpJ0Eq8bO55x9oCwT
4vCQWqE/Otrma6gmQWq/hyOZsFlb4Cssai25N6ZUMrwUUSn5pHCvqVKiVgTcmQSWbVbUEcOeTGzY
vxm+fMVwZcNrc+qcvb18czsff3M4PDh+CoaTp8lw/E3wTQTpi8H8V/iFaojIfHI0MuHBPE0PKK8Z
DAf0TwpQRfTZxSnE5O4n12i13RGQTWmddAfzsL9R/5zIUkx6H3Cbj8hbI+sQssVtdwxftqmIF71R
+29X2kNV0eMjlkkpehvjsvcZ+SbtDWwBlc33M/Dwk7YfmczoMV2bV4M96SCLAg6j7uhycdlXiyp7
HKY70Ax9xm7/Ygf4ZeAYv2dnHn6fcDCajg7xnzxcwL2vJ8ez44OpEOtxFETHIjo8Ho3XR2suxpPD
9fjoMB4HHMbZV0B7sSWl4We1Y3rBreVTjyHbmqSv6Ot/P3AjYts66km5TbOeqjRhvn5BJtkdK7N7
ocwHoe3h91CcACLTV4HmS5Qdp5fvjumPMjcfex34weDTp/8DsbTpmw==
===END CRASH DUMP===

**Comment by CortexPE** [comment]
update PMMP
