### ISSUE TITLE
Oh well, rip

### ISSUE THREAD

**Issue by Antisa14200** [CortexPE/TeaSpoon#133]
## Issue Description
Error while starting a server, latest version

## Steps to Reproduce
  Turning server on

## Crashdump, Backtrace or Other Files
[Server thread/CRITICAL]: ParseError: "syntax error, unexpected ';'" (EXCEPTION) in "TeaSpoon-master/src/CortexPE/utils/FishingRodLootTable" at line 78

**Comment by NycuRO** [comment]
Fixed, just wait publish my editing.
