### ISSUE TITLE
Mob AI & PureEntitiesX

### ISSUE THREAD

**Issue by LagHD** [CortexPE/TeaSpoon#134]
So I have this plugin installed with PureEntitiesX which means Mobs no longer have AI again so when I disable entites in this plugin's config, it also disables ender pearls & other entities rather than just mobs, could u make a separate configuration disabling just mobs ai on this plugin?

**Comment by NycuRO** [comment]
For me work.

**Comment by CortexPE** [comment]
it only disables mobs...
