### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Antisa14200** [CortexPE/TeaSpoon#135]
## Issue Description
Error

## Steps to Reproduce
1. turning on server (latest version)

## Crashdump, Backtrace or Other Files
[Server thread/CRITICAL]: TypeError: "base64_decode() expects parameter 1 to be string, null given" (EXCEPTION) in "TeaSpoon-master/src/CortexPE/utils/FishingRodLootTable" at line 81

**Comment by NycuRO** [comment]
Remove your config folder and try again.

**Comment by NycuRO** [comment]
wait @CortexPE for answer, idk, i don't have this error

**Comment by Antisa14200** [comment]
Do you have FishingRodLootTable on true in config.yml?

**Comment by NycuRO** [comment]
Yes.

**Comment by Antisa14200** [comment]
Oh then weird, @CortexPE waiting for you xd

**Comment by CortexPE** [comment]
delete cache.json... Its corrupted. that should regenerate a new cache.json file with a new LootTable.

**Comment by Antisa14200** [comment]
Alright thanks it works now.
