### ISSUE TITLE
Enchants Bug

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#137]
30.12 19:13:12 [Server] Server thread/CRITICAL Could not execute task CortexPE\checkTask: Index invalid or out of range
30.12 19:13:12 [Server] Server thread/CRITICAL RuntimeException: "Index invalid or out of range" (EXCEPTION) in "src/pocketmine/item/enchantment/Enchantment" at line 110

I don't have PiggyEnchants

I use VanillaEnchants Latest version

**Comment by CortexPE** [comment]
Update TeaSpoon
