### ISSUE TITLE
Add Devban and Cidban commands

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#138]
Pmmp had this way back and it seems like they removed the commands wondering if u can readd it

**Comment by NycuRO** [comment]
Useles..

**Comment by jojoe77777** [comment]
@BajanVlogs pmmp never had it, you mean Genisys?

**Comment by BajanVlogs** [comment]
Yes Genisys had it was wondering if u can bring it back because people can pass ip bans

**Comment by CortexPE** [comment]
Since CID can easily be changed and manipulated, its useless in banning
players.
But because XBL Authentication is forced in 1.2+ you can easily ban a
player's username and/or IP instead.

**Comment by BajanVlogs** [comment]
Yes Cortex but could u please have it I have a player that keeps making new accounts and using vpns unless u add a VPNGuard to teaspoon for we can disable and enable it then it should be good

**Comment by CortexPE** [comment]
VPN Blockers sadly aren't free...

Unless you're fine with rate limiting, its always paid...

**Comment by BajanVlogs** [comment]
Well could u add thess commands then

**Comment by CortexPE** [comment]
And CID bans won't do any better, it's even far worse.

**Comment by BajanVlogs** [comment]
Its harder for someone to get uncid banned rather than just making a new account and going on a vpn

**Comment by BajanVlogs** [comment]
You're 100% being like Dylan right now

**Comment by CortexPE** [comment]
How hard is it to get uncid banned:
1: Change clientId.txt
2: PROFIT!!!!

How hard is it to get unip banned:
1: Download VPN
2: Use VPN
3: Join a server you're banned in
4: PROFIT!!!!

How hard is it to get un-username-banned (XBL Author enabled):
1: Make a new email
2: Go through the 5 minute process of making an XBL Account
3: Join the server

See the difference?

**Comment by CortexPE** [comment]
If the spacing is fcked up, blame gmail.

**Comment by BajanVlogs** [comment]
Alot of kids on pc down know how to change the clientid could u just add it instead of argueing

**Comment by BajanVlogs** [comment]
Honestly Ill make my own version of TeaSpoon ill add it myself

**Comment by CortexPE** [comment]
"You're 100% being like Dylan right now" idk... As long as what you're arguing for is correct, You can go ahead and fight for it. Its the logic that I use and what other people do.

If Dylan didn't get my point of just extending PMMP and just letting me handle all these issues regarding this massive plugin, then let him. *you can't change the world* all I know is, I'm maintaining this big-a$$ plugin and will soon be using it for the server that I'll be making in a few months.
:shrug:

**Comment by CortexPE** [comment]
It's open source :shrug: ;)
Just do it in accordance with the AGPL License...
