### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by LagHD** [CortexPE/TeaSpoon#140]
Boats seem to make the server crash when u place it

**Comment by NycuRO** [comment]
Any error? You put the your problem, how can i fix them if you don't show any error on console?

**Comment by Antisa14200** [comment]
Do you have any info from crashdumb?

**Comment by LagHD** [comment]
@NycuRO just tried it again, it doesn't crash server but it disconnects me

**Comment by LagHD** [comment]
No console log since netherbox console hardly works

**Comment by Antisa14200** [comment]
Boats are not fully implemented in pmmp/teaspoon
And ik i had same bug

**Comment by Antisa14200** [comment]
Well yeah, it doesn't give you any crashdumps or errors
For me just says: Program CLI has stopped working (console crashes)

**Comment by CortexPE** [comment]
Boats aren't fully implement yet.

**Comment by LagHD** [comment]
Okay, is there any way to like disable boats from being placed so people don't crash the server?
