### ISSUE TITLE
Shulker Boxes Duplication Glitch

### ISSUE THREAD

**Issue by LagHD** [CortexPE/TeaSpoon#141]
## Issue Description
If you place a Shulker box, it stays in your inventory and also gets placed. = infinite Shulker boxes placing
## Steps to Reproduce
Place a Shulker box

**Comment by LagHD** [comment]
They can also get stacked by doing the dupe and breaking it again

**Comment by CortexPE** [comment]
Blame @NycuRO 😂 
I found where the bug occurs... Lemme just fix it and check his commit where he used if(<opposite statement>)return; instead of my method 😂

**Comment by CortexPE** [comment]
Including steps to reproduce sure does make issues easier to fix doesn't it?

**Comment by NycuRO** [comment]
@CortexPE Blame me, what?

**Comment by LagHD** [comment]
@CortexPE yes it does xD

**Comment by CortexPE** [comment]
Check ShulkerBox.php https://github.com/CortexPE/TeaSpoon/commit/f24ee60c57b15b9c67ea04fdc289f010f4301f43
