### ISSUE TITLE
Make Mobs Stack less lagg

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#145]

**Comment by NycuRO** [comment]
If you use PRX  , it's them problem.

TeaSpoon don't have any AI for them. So it's not tea spoon problem.
If you have problem with stacks, it's pmmp bug.

**Comment by BajanVlogs** [comment]
No make mobs stack not the eggs but when the mobs spawn

**Comment by NycuRO** [comment]
That's a TODO, not a error, #20 , thx.
