### ISSUE TITLE
Enchants don't work with AdvancedKits, Any ideas?

### ISSUE THREAD

**Issue by austina1212** [CortexPE/TeaSpoon#146]
## Issue Description

Enchantments are bugged and AdvancedKits doesn't work in result of that.
## Steps to Reproduce

1. Add AdvancedKits to server (https://poggit.pmmp.io/p/AdvancedKits)
2. do /kit testkit 
3. then it'll say in chat, an unknown error has occured. Then only gives you the items that are unenchanted from the kit

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by BajanVlogs** [comment]
Make sure u have latest advancedkits

**Comment by BajanVlogs** [comment]
or have latest pmmp

**Comment by Antisa14200** [comment]
You should get some type of error in console if there was an unknown error occured

**Comment by BajanVlogs** [comment]
Is the plugin updated with the EnchantAPI if not it won't work.

**Comment by BajanVlogs** [comment]
Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::setLevel()" (EXCEPTION) in "AdvancedKits.phar/src/AdvancedKits/Kit" at line 119

this is the error u are getting

**Comment by BajanVlogs** [comment]
https://poggit.pmmp.io/ci/BajanVlogs/AdvancedKits/AdvancedKits


Use my latest commit this fixes your issue

**Comment by CortexPE** [comment]
AdvancedKits is outdated.
someone should update it to the latest Plugin API
