### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#150]
Obsidian doesn't break with Efficnecy

**Comment by CortexPE** [comment]
Blame PMMP's AntiCheat
disable anti-instabreak in pocketmine.yml

**Comment by BajanVlogs** [comment]
@CortexPE  I already did

**Comment by BajanVlogs** [comment]
Its keep hapoening

**Comment by BajanVlogs** [comment]
Its from one of these commits u did

**Comment by CortexPE** [comment]
any errors?

**Comment by BajanVlogs** [comment]
Nope

**Comment by BajanVlogs** [comment]
Could u try and teoubleshoot it

**Comment by CortexPE** [comment]
reproduced
