### ISSUE TITLE
there are doubles  of items inmcpe creative inventory

### ISSUE THREAD

**Issue by coolkidsrule101** [CortexPE/TeaSpoon#151]
pic will be upload at 5pm bc im in school right now

**Comment by Antisa14200** [comment]
Probably because one item is from Teaspoon while another one is from Pocketmine but not implemented yet

**Comment by CortexPE** [comment]
what items?

**Comment by CortexPE** [comment]
![image](https://user-images.githubusercontent.com/17762324/34519526-13ce2ade-f04a-11e7-8b66-080c60966aa8.png)
![image](https://user-images.githubusercontent.com/17762324/34519530-17be2da6-f04a-11e7-8791-1f077c8a98f2.png)
![image](https://user-images.githubusercontent.com/17762324/34519532-1a9bab20-f04a-11e7-82fe-d892b3e879f3.png)
![image](https://user-images.githubusercontent.com/17762324/34519538-1eef4baa-f04a-11e7-848f-d8cd4a019ff6.png)
Seems all fine to me 🤷‍♂️

**Comment by Antisa14200** [comment]
@CortexPE He probably meant 2 types of chorus fruit, boats...

**Comment by coolkidsrule101** [comment]
I'll get the picture today to show you
