### ISSUE TITLE
efficiency glitch

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [CortexPE/TeaSpoon#152]
## Issue Description

A short description about the issue
Pickaxes With efficiency takes x3 breaks or more some reported x8 breaks, to actually break the block. Ik this is from pmmp anticheat, but cant u fix? If I disable pmmp anticheat nuker cheaters will ruin my worlds.
## Steps to Reproduce

1. ... Enchant a pickace with efficiency 3
2. ... Mine
3. ... Results

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by NycuRO** [comment]
flights = false

**Comment by CortexPE** [comment]
Blame PMMP :joy:
