### ISSUE TITLE
dupe glitch

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [CortexPE/TeaSpoon#157]
## Issue Description

A short description about the issue
Players dupe armor using your vanilla right click equip
## Steps to Reproduce

1. ...  place a item frame, get armor in hand
2. ... Right click, it will equip and put in frame at same time
3. ...

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by TDMidkwhatisxd** [comment]
done please read and fix asap players dupe

**Comment by TDMidkwhatisxd** [comment]
I added steps

**Comment by CortexPE** [comment]
Lemme test it and commit a patch after fixing it...

**Comment by TDMidkwhatisxd** [comment]
Ok, if u cant reproduce give me test sv ip

**Comment by TDMidkwhatisxd** [comment]
wrong steps, read again xd

**Comment by CortexPE** [comment]
makes sense... lemme just wait till my script auto-updates PMMP so I can start fixing it 😂 
![image](https://user-images.githubusercontent.com/17762324/34607544-cc13f2aa-f1d9-11e7-9d6b-d6717ed70975.png)

**Comment by CortexPE** [comment]
issue is fixed... just going to check if it's still the same on vanilla

**Comment by CortexPE** [comment]
yep. fixed.

**Comment by TDMidkwhatisxd** [comment]
yay, thx .... anyway nice plugin .....

**Comment by CortexPE** [comment]
I haven't added the commit yet xD

**Comment by TDMidkwhatisxd** [comment]
I saw :))))))

**Comment by TDMidkwhatisxd** [comment]
hehehe thanxs
