### ISSUE TITLE
Copying and paste. 

### ISSUE THREAD

**Issue by DrewD3V** [CortexPE/TeaSpoon#16]
Hello Cortex, I'm a member of RealDevs, which owns TableSpoon, it appears you have copied some code from TableSpoon without credits. I request that you add some credits or remove the code. The code is the EnderChest code. Thank you.

**Comment by CortexPE** [comment]
The only copy-pasted file from TableSpoon is EnderChestInventory... I'd recommend you to add something like: [A Copyright Header](https://github.com/CortexPE/TeaSpoon/blob/master/src/CortexPE/entity/projectile/Snowball.php#L2-L20)
to prevent issues like this from happening.

To resolve it, I'll just add one to credit the organization who made it.
