### ISSUE TITLE
Bottle o enchanting not working

### ISSUE THREAD

**Issue by WaldoFS** [CortexPE/TeaSpoon#165]
## Issue Description
I using bottle o enchanting, and error

## Steps to Reproduce

1. throw bottle o enchanting
2. The bottle is fly with error code
3. ...

## Crashdump, Backtrace or Other Files
Could not tick level "xxx" : Call to undefined method pocketmine\level\Level::dropExperience
Error: "Call undefinied method pocketmine\level\Level::dropExperience()

**Comment by CortexPE** [comment]
update PMMP
