### ISSUE TITLE
Big DUPE GLITCH

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [CortexPE/TeaSpoon#168]
## Issue Description

A short description about the issue

## Steps to Reproduce

1. ... Watch video
2. ... Watch it Again
3. ... Profit?

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```
https://youtu.be/45Y-kafU8fo

**Comment by TDMidkwhatisxd** [comment]
Player Who reported: Pls don't fix, I need to dupe some stuff .... and now he go dupe before u fix it xd

**Comment by CortexPE** [comment]
seems to be a problem with shulkerboxes...
Will be fixed in a few minutes... Please wait 😉

**Comment by CortexPE** [comment]
it doesnt update the shulkerbox's Item tag thats why it dupes

**Comment by CortexPE** [comment]
lemme just test it

**Comment by NycuRO** [comment]
@TDMidkwhatisxd aster?
