### ISSUE TITLE
XP FREEZE

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [CortexPE/TeaSpoon#169]
## Issue Description

A short description about the issue

## Steps to Reproduce

1. ... kill someone with fire aspect sword, and let it die by fire
2. ... There will be a xp orb that follow all players
3. ... Server will freeze afterwards

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```No crash, no errors.

**Comment by TDMidkwhatisxd** [comment]
Can u add a way to disable xp orbs?

**Comment by CortexPE** [comment]
Blame PMMP xD

**Comment by TDMidkwhatisxd** [comment]
you knew about that?

**Comment by TDMidkwhatisxd** [comment]
If I report this pmmp staff and users will make fun of me .. ;----;

**Comment by CortexPE** [comment]
try it w/o plugins then report it to them (W/O PLUGINS [even TeaSpoon])

**Comment by TDMidkwhatisxd** [comment]
naaah, if they see teaspoon , ill get ignored, topic closed , or rank noob, or even worse, banned .

**Comment by CortexPE** [comment]
#BlamePMMP xd

**Comment by TDMidkwhatisxd** [comment]
I was like why my main server freeze and anarchy don't? Then after tests, I saw a map were players always pvp with ms 90000..... or more.... after I froze I did /status and waited a lot.
 I deleted map, and saw again freeze, after a xp orb was drunk and didn't know who to follow :))))

**Comment by TDMidkwhatisxd** [comment]
Cant u add a option to disable xp? Is a useless feature, so useless....

**Comment by CortexPE** [comment]
Exactly.

**Comment by CortexPE** [comment]
Why disable it?

**Comment by TDMidkwhatisxd** [comment]
Because is useless and freeze server....

**Comment by CortexPE** [comment]
you can ask PMMP for that

**Comment by TDMidkwhatisxd** [comment]
Naaah , I cant ask anything from them or rage , wen i complained about instabreak #dktappsminions already set to eat me :)))) ... then deleted thread

**Comment by TDMidkwhatisxd** [comment]
They wanna dev rank so bad.

**Comment by CortexPE** [comment]
> Naaah , I cant ask anything from them or rage , wen i complained about instabreak #dktappsminions already set to eat me :)))) ... then deleted thread

Exactly 😂

**Comment by TDMidkwhatisxd** [comment]
You cant add a option to disable it? Think of it as a feature ^^

**Comment by CortexPE** [comment]
it'd need to override a lot of things.

**Comment by TDMidkwhatisxd** [comment]
Any idea how to avoid this?

**Comment by TDMidkwhatisxd** [comment]
https://forums.pmmp.io/threads/xp-orbs-glitch.5033/#post-46030
If u wanna see dktappsminions rage, check this thread later :)))))

**Comment by TDMidkwhatisxd** [comment]
from what I see pmmp and your plugin have drop experience function, its not called x2 times? I will edit Teaspoon to disable xp and use a older pmmp

**Comment by CortexPE** [comment]
kk you can disable XP in EventListener and EnchantingBottles...

**Comment by TDMidkwhatisxd** [comment]
yap
