### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#174]
This has been a error in pocketmine for awhile

14.01 11:54:32 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\permission\BanEntry::setExpires() must be an instance of DateTime or null, boolean given, called in phar:///custom-php7.2.phar/src/pocketmine/permission/BanEntry.php on line 136" (EXCEPTION) in "src/pocketmine/permission/BanEntry" at line 80

**Comment by CortexPE** [comment]
This isnt TeaSpoon's problem
