### ISSUE TITLE
Ender Pearl Cannot cooldown

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [CortexPE/TeaSpoon#175]
EnderPearl cooldown doesn’t work you can spamm it fix it pls if you can thx.

**Comment by CortexPE** [comment]
I will when I'm not busy anymore... :/

~ Reply sent with my phone

**Comment by xXNiceAssasinl0** [comment]
K

**Comment by CortexPE** [comment]
are you using Latest build?
Its working fine on me...

**Comment by xXNiceAssasinl0** [comment]
Hmm...  no

**Comment by CortexPE** [comment]
Update it 😂

**Comment by xXNiceAssasinl0** [comment]
@CortexPE for some reason I can spam Ender pearl when I hit once
