### ISSUE TITLE
Xp Issue

### ISSUE THREAD

**Issue by BajanVlogs** [CortexPE/TeaSpoon#176]
16.01 14:49:05 [Server] Server thread/CRITICAL Could not tick level "world": Call to undefined method pocketmine\Player::getTotalXp()
16.01 14:49:05 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Player::getTotalXp()" (EXCEPTION) in "TeaSpoon_dev-102.phar/src/CortexPE/utils/Xp" at line 59

**Comment by BajanVlogs** [comment]
and don't say update pmmp
its already updated

**Comment by CortexPE** [comment]
Update TeaSpoon
