### ISSUE TITLE
Spawner Dulibcation

### ISSUE THREAD

**Issue by optimusprime338** [CortexPE/TeaSpoon#179]
## Issue Description

Spawners can easly be dublicated by just placing them!
https://www.youtube.com/watch?v=TveipFhLJkU
Version:- Dev #121 (&8608)
Pmmp:- 1.7dev-625
## Steps to Reproduce

1. take spawner (make sure in survival mode)
2. place them, spawners remains same in inventory! like if had 3 and place 1, you will have still 3 spawners

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by CortexPE** [comment]
it works fine for me... You probably have a plugin that interferes with TeaSpoon's MobSpawners or makes it so that if they place a spawner its count doesn't decrease

**Comment by optimusprime338** [comment]
I just double checked! 
I have no plugins installed..
using teaspoon dev 121
pmmp 1.7dev634
@CortexPE

**Comment by teracube** [comment]
@optimusprime338 
solved for you ?
thanks
