### ISSUE TITLE
Two errors while starting a console

### ISSUE THREAD

**Issue by Antisa14200** [CortexPE/TeaSpoon#181]
## Issue Description
2 errors above appear while turning on a server with the latest version of PMMP
## Steps to Reproduce
1. Turning the server on, checking console

## Crashdump, Backtrace or Other Files

 [Server thread/CRITICAL]: ErrorException: "Declaration of CortexPE\item\Boat::onActivate(pocketmine\level\Level $level, pocketmine\Player $player, pocketmine\block\Block $block, pocketmine\block\Block $target, int $face, pocketmine\math\Vector3 $facepos): bool should be compatible with pocketmine\item\Item::onActivate(pocketmine\Player $player, pocketmine\block\Block $blockReplace, pocketmine\block\Block $blockClicked, int $face, pocketmine\math\Vector3 $clickVector): bool" (EXCEPTION) in "TeaSpoon-master/src/CortexPE/item/Boat" at line 90

[Server thread/CRITICAL]: ErrorException: "Declaration of CortexPE\item\FlintSteel::onActivate(pocketmine\level\Level $level, pocketmine\Player $player, pocketmine\block\Block $blockReplace, pocketmine\block\Block $blockClicked, int $face, pocketmine\math\Vector3 $facePos): bool should be compatible with pocketmine\item\FlintSteel::onActivate(pocketmine\Player $player, pocketmine\block\Block $blockReplace, pocketmine\block\Block $blockClicked, int $face, pocketmine\math\Vector3 $clickVector): bool" (EXCEPTION) in "TeaSpoon-master/src/CortexPE/item/FlintSteel" at line 140

**Comment by BajanVlogs** [comment]
Update PMMP to latest also update TeaSpoon to latest

**Comment by Antisa14200** [comment]
I do have both on the latest version

Dana 25. sij 2018. 19:41 osoba "BajanVlogs" <notifications@github.com>
napisala je:

**Comment by Antisa14200** [comment]
Its prob a issue since this new bigger update of teaspoon idk

Dana 25. sij 2018. 19:44 osoba "Ante Dragobratović" <aroniarni73@gmail.com>
napisala je:

**Comment by Antisa14200** [comment]
Those changes seems to be a cause of these https://github.com/pmmp/PocketMine-MP/commit/6c8a1a5b80e9700cdbeb92adf4146fd9a0d299dc

**Comment by CortexPE** [comment]
Reproduced...
Just fixing it and I'll push changes

**Comment by CortexPE** [comment]
fixed https://github.com/CortexPE/TeaSpoon/commit/0daac7dfe6020f6d25a0e202abde7374c833507b
