### ISSUE TITLE
Cannot Load TeaSpoon

### ISSUE THREAD

**Issue by CupidonSauce173** [CortexPE/TeaSpoon#182]
## Issue Description
I cannot load the TeaSpoon (Lasted version) on my server. Here is some informations 
Server version :
PocketMine-MP 1.7dev-516 API 3.0.0-ALPHA10.
Plugin Version : 
TeaSpoon_dev-125.

## Steps to Reproduce
1. Drop the .phar (or master) in the plugins files.
2. Reload or Restart the server.

Error Code
[Server thread/CRITICAL]: ErrorException: "include(phar:///root/plugins/TeaSpoon_dev-124.phar/src/CortexPE/item/LingeringPotion.php): failed to open stream: phar error: Cannot open phar archive "/root/plugins/TeaSpoon_dev-124.phar" for reading" (EXCEPTION) in "vendor/pmmp/pocketmine-spl/BaseClassLoader" at line 128.

**Comment by tiNsLeY799** [comment]
Either your PMMP version is outdated, or you have a version of TeaSpoon that has lingering potions.

**Comment by CortexPE** [comment]
His/her PMMP Version is outdated... "1.7dev-516"
