### ISSUE TITLE
Can not use custom inventory like beacons

### ISSUE THREAD

**Issue by GooglePlugin** [CortexPE/TeaSpoon#183]
## Issue Description

After I touched a beacon(or hopper), It opened a inventory. But when I put item in it, the item would back to my inventory.
I think it is a inventory anti-cheat bug like Genisys.

## Steps to Reproduce

1. ...
2. ...
3. ...

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by GooglePlugin** [comment]
It is my concole debug message:
[Server thread/DEBUG]: Unhandled inventory action from XingKong6: Player XingKong6 has no open container with window ID -24

**Comment by GooglePlugin** [comment]
It is my console message:
[Server thread/DEBUG]: Unhandled inventory action from XingKong6: Player XingKong6 has no open container with window ID -24

**Comment by CortexPE** [comment]
beacons aren't fully implemented yet... but you can put in items in the inventory and effects with plugins
