### ISSUE TITLE
Debug is always on

### ISSUE THREAD

**Issue by isoz** [CortexPE/TeaSpoon#184]
For some reason this plugin is causing debug mode to be always on despite what's set on pocketmine.yml

Probably this 
https://github.com/CortexPE/TeaSpoon/commit/a1e61fc9c3aceef0ea1c097c137da4de439fd214

**Comment by CortexPE** [comment]
unpackaged source code automatically enables TeaSpoon's debug mode...
to disable it, use poggit builds.
