### ISSUE TITLE
Splash Potion 

### ISSUE THREAD

**Issue by SpecialistNinja** [CortexPE/TeaSpoon#185]
Splash Potion stop working when there is an area from iProtector (plugin) created

When i deleted an area from iProtector the Splash Potion work again

**Comment by CortexPE** [comment]
your iProtector version cancels EntitySpawnEvent in protected areas... (Probably to prevent Arrows and TNT)

edit it maybe?

**Comment by SpecialistNinja** [comment]
but it not only happen inside protect area
