### ISSUE TITLE
Make support for latest pmmp please?

### ISSUE THREAD

**Issue by SpecialistNinja** [CortexPE/TeaSpoon#188]
## Issue Description

A short description about the issue

## Steps to Reproduce

1. ...
2. ...
3. ...

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by SpecialistNinja** [comment]
@xXNiceAssasinl0 Me?

**Comment by xXNiceAssasinl0** [comment]
No @CortexPE is banned from pmmp.

**Comment by SpecialistNinja** [comment]
@xXNiceAssasinl0 oh rip :/ but whyyyyy

**Comment by xXNiceAssasinl0** [comment]
He have some bad code for poggit

**Comment by xXNiceAssasinl0** [comment]
Rumors xD

**Comment by SpecialistNinja** [comment]
Well what now

**Comment by CortexPE** [comment]
this should work... It works on my machine xD
