### ISSUE TITLE
Shulker Boxes

### ISSUE THREAD

**Issue by LagHD** [CortexPE/TeaSpoon#191]
## Issue Description
Shulker Boxes are useless / alternative for trash bins xD

## Steps to Reproduce
1. Place Shulker Box
2. Put an item inside
3. Break box
4. Place it again
5. Open it, (it'll be empty)

## Next Bug:
■ Shulker Boxes place upside-down  (ye ik it's a well know bug but it's annoying lol)

**Comment by xXNiceAssasinl0** [comment]
2+2?
