### ISSUE TITLE
Fix Heartbeat error

### ISSUE THREAD

**Issue by austina1212** [CortexPE/TeaSpoon#194]
I get this error in my console: (10.02 20:43:50 [Server] Server thread/DEBUG #3 src/pocketmine/scheduler/ServerScheduler(326): pocketmine\scheduler\TaskHandler->run(integer 28721)
10.02 20:43:50 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2531): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 28721)
10.02 20:43:50 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2274): pocketmine\Server->tick()
10.02 20:43:50 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2149): pocketmine\Server->tickProcessor()
10.02 20:43:50 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1737): pocketmine\Server->start()
10.02 20:43:50 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(554): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
10.02 20:43:50 [Server] Server thread/DEBUG #9 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php) I am not 100% if all of those errors are to do with heartbeat but it really needs to be fixed with spawners...

**Comment by CortexPE** [comment]
pretty sure this isnt caused by teaspoon

**Comment by austina1212** [comment]
Nevermind

**Comment by austina1212** [comment]
Nevermind, realized my Mob Stacker plugin is broken.. RIP hopefully I can find someone to fix it/a new one. Sorry for wasting your time
