### ISSUE TITLE
Enchants

### ISSUE THREAD

**Issue by diamondgamermcpe** [CortexPE/TeaSpoon#2]
Just wanna say there’s no a working plugin called VanillaEnchants fully functional by AZ.

**Comment by diamondgamermcpe** [comment]
I didn’t meant to write no...

**Comment by GDRGamingzz** [comment]
Hi @diamondgamermcpe,

you could use @TheAz928's Vanilla Enchants for working enchants.

**Comment by GDRGamingzz** [comment]
the latest build on az's vanilla enchants are working now. just to let you know @diamondgamermcpe

**Comment by diamondgamermcpe** [comment]
@GDRGamingzz I didn’t meant to write no...

**Comment by TheAz928** [comment]
lol

**Comment by GDRGamingzz** [comment]
lmao well close this issue if its already done xD
