### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by CortexPE** [CortexPE/TeaSpoon#20]
### TODO List:
 - Ender Portal Checks
 - Proper Nether dimension death
 - Redstone System *(If Possible and Not-That-Laggy)*
 - MobAI *(If Possible and Not-That-Laggy)*
 - Fix ShulkerBox rotation

**Comment by akaSnapy** [comment]
You should start with spawners

**Comment by CortexPE** [comment]
@akaSnapy Any ideas about it's new NBT Structure? xD (Just asking)

**Comment by thebaconradio** [comment]
start with spawners

**Comment by NycuRO** [comment]
@CortexPE Redstone from Steadfast2 , if you want.

Enchanting Tables you can add enchanting and enchantments optionals? I want use other plugin, same with MobAi?

**Comment by XDqrkneZ** [comment]
Hoppers

**Comment by shdudwns** [comment]
Piston
Ride mob
Ride minecart and boat
Please

**Comment by LolNova** [comment]
enchantssss

**Comment by akaSnapy** [comment]
@CortexPE nope, IT got really fucked up after 1.1

**Comment by XDqrkneZ** [comment]
Better ender pearl (animation?) Make players able to throw Ender Pearls farther

**Comment by CortexPE** [comment]
@XDqrkneZ You just gotta aim a better angle 😉

**Comment by NycuRO** [comment]
@CortexPE Hello, discord?

**Comment by BlawoHD** [comment]
Please add Armor Stand

**Comment by BajanVlogs** [comment]
add where we can disable some stuff ingame like lightning and other cool stuff 

also make where dispensers shoot primed tnt like pc version

**Comment by teracube** [comment]
hi,

is it a finalized version. can i test it on my server ?
what mean "5 problems" at the column lint on the latest build
https://poggit.pmmp.io/ci/CortexPE/TeaSpoon/TeaSpoon

thanks

**Comment by CortexPE** [comment]
@BajanVlogs Ability to disable lightning? Sure... Working Dispensers? Maybe soon... When the Redstone system gets implemented

@teracube They're Lint checks to check if the code follows PMMP's Code Standard... The lint "problems" that are displayed right now are not errors... They're warnings that they violate PMMP's Code Standard. You can test it and use it on production right now.... It's stable (afaik) but you can report bugs in this issues section (if you find any) 😄

**Comment by teracube** [comment]
@CortexPE 
are TeaSpoon entities and mobs finished or planned ?
thanks

**Comment by CortexPE** [comment]
@teracube they're registered but without AI so you can spawn them with spawn eggs

**Comment by BajanVlogs** [comment]
Add working fishing rods

**Comment by JackMD** [comment]
How about adding extended/working functionality for farms with custom speed rate for crop growth!

**Comment by teracube** [comment]
@CortexPE 
is it possible to use TeaSpoon and PiggyCustomEnchants on a server 
if yes what about enchantments config on confiz.yml : register true or register false ?

enchantments:
 # Weather to enable & register Vanilla Enchantments (Set to false if you're going to use VanillaEnchantments plugin etc...) or not
 register: true

**Comment by CortexPE** [comment]
@teracube yeah... without changing that value.

**Comment by BajanVlogs** [comment]
Lets go with Jacks Idea For Custom crop growth

**Comment by Letboes** [comment]
Please add the Spawners 😍!!

**Comment by TheNewManu** [comment]
For spawners and mob use PureEntitiesX :)

**Comment by BajanVlogs** [comment]
Enchants are added Spawners are coming soon also PureEntities will mess with TeaSpoon

**Comment by CortexPE** [comment]
@BajanVlogs you can disable "entities.register" [in this line](https://github.com/CortexPE/TeaSpoon/blob/master/resources/config.yml#L17) to let PureEntitiesX take over Mobs (not-including some entities & projectiles which aren't handled by PEX [afaik])...

**Comment by BajanVlogs** [comment]
Well can u work on Fishing Rods that work plz

**Comment by teracube** [comment]
@CortexPE 
can you please reopen issue #61
Awzaw staff PMMP suggest to add this before getId()

PHP:
if (!$p->isOnline()){
return;
}

**Comment by teracube** [comment]
@CortexPE 
i suggest add throw snowballs for christmas ;-)

**Comment by CortexPE** [comment]
snowballs already work...

**Comment by teracube** [comment]
Oops

**Comment by BlawoHD** [comment]
@CortexPE Please add armor stand

**Comment by optimusprime338** [comment]
@CortexPE hoppers!!

**Comment by TDMidkwhatisxd** [comment]
Teaspoon need more Vanilla-Like features...
1. Make boats work
2. ADD basic redstone , just doors , redstone lantern, stuff that is not complex...
3. Is there elytra recipe?
4. Make AL for some mobs, like Pig , Chicken ... AL should not be complex , just rand walking...
5. I don't know if u can make enchant table work...

**Comment by SuperKali** [comment]
add armor stand

**Comment by alair069** [comment]
Pls, Add ArmorStand

**Comment by CortexPE** [comment]
-- Dec 13 2017 --
Monster Spawners have been added

**Comment by optimusprime338** [comment]
@CortexPE u are awesome! haha

**Comment by BajanVlogs** [comment]
-- Dec 17 2017 --
Minecarts with Redstone has been added

**Comment by optimusprime338** [comment]
what?

**Comment by BlawoHD** [comment]
ArmorStands

**Comment by 0pGam3rMC** [comment]
Just curious as of today 12-22-2017 is vanilla enchants working ?

**Comment by CortexPE** [comment]
Yeah @0pGam3rMC

**Comment by shdudwns** [comment]
CommandBlock and pistone

**Comment by shdudwns** [comment]
@CortexPE

**Comment by teracube** [comment]
yes Redstone System ;-)
thanks

**Comment by SuperKali** [comment]
@CortexPE i have question, but teaspoon plugin uses many task, because i use this plugin and i have high load and my server dropped the performance

**Comment by CortexPE** [comment]
@SuperKali I'll try to fix all performance issues on the next commit 😉 
(I'll be using this plugin in the server that I'll be working on soon)

**Comment by LagHD** [comment]
Enchants works, they are great! It's just that the enchanting tables don't work, when u put an item into the table it takes it back out

**Comment by JackMD** [comment]
Thats because its not implemented in the core i.e. PocketMine-MP

**Comment by LagHD** [comment]
Oh xD, would this plugin work on a different server core?

**Comment by CortexPE** [comment]
Nope. It'd disable itself to prevent interfering with the other core's
features...

**Comment by teracube** [comment]
make enchant table work
possible ?

**Comment by LagHD** [comment]
Ender Crystals needed

**Comment by TDMidkwhatisxd** [comment]
Enchant Tables are Client Side, server cant check if player enchanted a item.
Allowing server side enchantment means to allow items cheat. Like how genisys did, there was a option to  allow inventory cheats to allow enchant table.

**Comment by teracube** [comment]
i can not find quartz on nether world
is it normal ?
thanks

**Comment by Alderander** [comment]
and I will only say that you do a good job, thanks for that ;)

**Comment by CortexPE** [comment]
I might translate NukkitX's Nether Generator instead @teracube as @NycuRO suggested a few months ago 😂

**Comment by NycuRO** [comment]
hmm?

**Comment by Adam1609** [comment]
Suggestion: Adding Keep Inventory and Experience <3

**Comment by austina1212** [comment]
Add protection as Pocketmine's protection is broken

**Comment by austina1212** [comment]
Add a Mob stacker

**Comment by SuperOP535** [comment]
mob stacker should be a seperate plugin

**Comment by XoticRealmsOwnerandDev** [comment]
make it where spanwers can blow up from tnt and creeper eggs and drop the spawners

**Comment by daniktheboss** [comment]
Omg, this is why teaspoon is ugly af. You try to put all the features everyone asks for, and put it in one pluguin

**Comment by CortexPE** [comment]
Why are you here @daniktheboss ?

In case you haven't read it yet, I've told everyone who hates TeaSpoon to just gtfo and stop bothering us...

Excerpt from README.md:
> If you don't like it / hate it, Then don't even bother using it. It's that simple... TeaSpoon was made for those who need it. 😉 

Excerpt from the Wiki page: 
> Why was this plugin even made?
        This plugin's intention was to help servers to have a more vanilla-like experience without directly changing PMMP's code unlike spoons nor forks.

> Why not use separate plugins instead of a massive one to make it more modular?
        Because, due to the (usual) daily updates to PMMP, Plugins get outdated with the latest plugin API. If I were to make this modular, updating every plugin to work with the latest PMMP version would be a headache (take a look at the features list).

> Your implementation of < a feature on TeaSpoon > isn't correct!
        Well, you're very welcome to open a Pull Request and use your own method of doing it and if it's correct, I'll surely merge it. I usually don't want to over-complicate things to make them more readable and self-explanatory for the future, And over-complicating things has its downsides.

> I (don't like/hate) your plugin!
        Simple. Just don't use it nor even bother looking at it (if you're that butt-hurt). This plugin was made for those who need it. I never forced anyone to use it.

![gtfo](https://user-images.githubusercontent.com/17762324/37090451-0b1e0cc2-21ca-11e8-8451-7f35c4dcee11.gif)

**Comment by XoticRealmsOwnerandDev** [comment]
add a way to make chunks load if their is like a horse spawner in the chunk this would be nice for some servers but also make it able to be turned off and on in the config.yml

**Comment by lukeeey** [comment]
Extra commands to implement: http://pe.thediamondyt.tk/wiki/software/pocketmine/todo/

**Comment by XuPaperCup** [comment]
Please make railway and Minecraft work,I need to use them.

>

**Comment by teracube** [comment]
@CortexPE 
swimming
thanks

**Comment by teracube** [comment]
@CortexPE 
hi CortexPE ; - )
could you please upgrade TeaSpoon with stable build PMMP dev 1201
thanks

**Comment by teracube** [comment]
@CortexPE 
upgrade TeaSpoon on API 3.0.0 and 4.0.0
do you have time Cortex ; - )
thanks

**Comment by teracube** [comment]
sit in chairs (like plugin OturmaChairs)
Redstone System
minecart

thanks
