### ISSUE TITLE
Mob-related methods malfunctioning

### ISSUE THREAD

**Issue by GiantQuartz** [CortexPE/TeaSpoon#202]
## Issue Description
The most of the mob-related methods, such as `teleport()` or `despawnFromAll()` don't work correctly, which is a big inconvenient for developers trying to use them.

**Comment by CortexPE** [comment]
Experienced this issue while trying to make a bait entity for IOTADevs/Agent... But TeaSpoon never actually messed with those methods...

**Comment by CortexPE** [comment]
This might be PMMP's issue... Maybe try removing TeaSpoon then test your plugin?

**Comment by CortexPE** [comment]
confirmed non tsp issue...

**Comment by CortexPE** [comment]
https://forums.pmmp.io/threads/entity-teleport-is-not-working.5351/
