### ISSUE TITLE
anvil

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [CortexPE/TeaSpoon#203]
## Issue Description

A short description about the issue
Players report that anvil make items vanish
## Steps to Reproduce

1. ... Craft anvil
2. ... Use it
3. ... Profit?

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by CortexPE** [comment]
known issue. read readme
