### ISSUE TITLE
Unable to load up

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [CortexPE/TeaSpoon#205]
## Issue Description

A short description about the issue

18.02 17:10:48 [Server] Server thread/INFO Enabling TeaSpoon v1.0.0
18.02 17:10:48 [Server] Server thread/INFO Loading...
18.02 17:10:48 [Server] INFO .-.                                               .-.                    
18.02 17:10:48 [Server] INFO (_) )-.                                  /   .--.-'                       
18.02 17:10:48 [Server] INFO /   \    .-.  .    .    .-.  ).--.---/---(  (_).-.  .-._..-._..  .-.   
18.02 17:10:48 [Server] INFO /     \ ./.-'_/ \  / \ ./.-'_/       /     `-.  /  )(   )(   )  )/   )  
18.02 17:10:48 [Server] INFO .-/.      )(__.'/ ._)/ ._)(__.'/       /    _    )/`-'  `-'  `-'  '/   (   
18.02 17:10:48 [Server] INFO (_/  `----'     /    /                      (_.--'/                      `- 
18.02 17:10:48 [Server] INFO An old apple welcomes spring!
18.02 17:10:48 [Server] INFO Copyright (C) CortexPE 2017-2018
18.02 17:10:48 [Server] Server thread/ALERT This plugin has been tested on PocketMine version: 1.7dev-721, running it on older PocketMine versions is very unstable. To prevent any futher in-compatibility issues, TeaSpoon will now disable itself.

## Steps to Reproduce

1. ...
2. ...
3. ...

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by DelxHQ** [comment]
Download the lastest PMMP build (https://github.com/pmmp/PocketMine-MP/releases/download/1.7dev-743/PocketMine-MP.phar) then try

**Comment by Antisa14200** [comment]
Try with latest PMMP and Teaspoon plugin versions

**Comment by CyanCreeper** [comment]
I did. Same thing...

**Comment by CortexPE** [comment]
If you are on a MultiCraft host, e.g. Ramshard, load the latest PMMP version as custom phar

**Comment by CyanCreeperPlayz** [comment]
Thank you, it works. Great job on the plugin.
