### ISSUE TITLE
Hoppers

### ISSUE THREAD

**Issue by Tumeden** [CortexPE/TeaSpoon#211]
Hoppers DO work,  however they DONT connect to each other.

Is this functionality able to be added please?  It's generally how its suppose to work but currently missing from teaspoon.

**Comment by CortexPE** [comment]
They do work on my tests :/

**Comment by CortexPE** [comment]
They also work when connected to each other

**Comment by Tumeden** [comment]
I'm using the latest stable PMMP build and they don't connect for me at all.
