### ISSUE TITLE
Bug (God Apple)

### ISSUE THREAD

**Issue by SpecialistNinja** [CortexPE/TeaSpoon#214]
Basically i test God Apple with Teaspoon, but once i eat god apple it didnt regen quick enough and people can still outhit God Apple and kill me

When i removed Teaspoon, god apple work and people can no longer outhit it

**Comment by KielKing** [comment]
TeaSpoon does not edit the enchanted golden apple item, as i think

**Comment by SpecialistNinja** [comment]
@KielKing Test it, install teaspoon and let someone hit u constantly and test it without teaspoon and u will see what i mean

**Comment by KielKing** [comment]
I don't have anyone to test with @SpecialistNinja

**Comment by KielKing** [comment]
@SpecialistNinja have a twitter? Or discord?

**Comment by SpecialistNinja** [comment]
add me Kist #3326

**Comment by SpecialistNinja** [comment]
or what is your discord? I'll add you

**Comment by CortexPE** [comment]
Enchanted Golden Apples aren't modified by TeaSpoon.

**Comment by SpecialistNinja** [comment]
But me and @kielking already test it and he even said it was from teaspoon

**Comment by KielKing** [comment]
@CortexPE the problem is with absorbtion, it doesn't take the damage 100%

**Comment by LagHD** [comment]
Maybe It's to do with difficulty mode
Btw check pmmp latest commit they fixed something to do with absorption and god apples

**Comment by CortexPE** [comment]
This issue is pretty stale :/
so here's my tests I did on latest commit :
https://www.youtube.com/watch?v=qzRtVlXPFtQ

Works pretty normally... idk what you're experiencing... 🙁
