### ISSUE TITLE
Latest pmmp crash.

### ISSUE THREAD

**Issue by Tumeden** [CortexPE/TeaSpoon#217]
PocketMine-MP Crash Dump Sat Mar 10 10:16:55 AST 2018

Error: Class CortexPE\item\Elytra contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (pocketmine\item\Durable::getMaxDurability)
File: TeaSpoon_dev-147.phar/src/CortexPE/item/Elytra
Line: 46
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: TeaSpoon v1.0.0

Code:
[37] 
[38] use pocketmine\item\{
[39] 	Armor, Item
[40] };
[41] 
[42] class Elytra extends Armor {
[43] 	public function __construct($meta = 0){
[44] 		parent::__construct(Item::ELYTRA, $meta, "Elytra Wings");
[45] 	}
[46] }
[47] 
[48] 
[49] 
[50] 
[51] 
[52] 
[53] 
[54] 
[55] 
[56

Backtrace:

PocketMine-MP version: 1.7dev #816 [Protocol 201; API 3.0.0-ALPHA11]
Git commit: bd3d2451bc13b35a280bd02bb0f3584cdbd90eee
uname -a: Linux mcpe1 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64
PHP Version: 7.2.2
Zend version: 3.2.0
OS : Linux, linux

**Comment by Antisa14200** [comment]
I already reported the following on the https://github.com/CortexPE/TeaSpoon/issues/216
