### ISSUE TITLE
Two-In-1 Bugs

### ISSUE THREAD

**Issue by LagHD** [CortexPE/TeaSpoon#222]
## Issue Description
First Issue: Ender crystals can be placed on any block
2nd Issue: Shulker Boxes can be placed inside Shulker Boxes recurring. (Unlimited inventory)

## Steps to Reproduce
First Issue: Well place an ender crystal anywhere xd
2nd Issue: Place SB, Place Hopper on SB, put an SB inside hopper
## Crashdump, Backtrace or Other Files
Irrelevant

**Comment by CortexPE** [comment]
Wait I thought ShulkerBox checks were done ClientSide so because of my laziness I didn't bother checking the transaction... wtf mojang

**Comment by CortexPE** [comment]
O nvm

**Comment by CortexPE** [comment]
Still good way of cheating the system tho

**Comment by CortexPE** [comment]
2nd issue is how it works in vanilla

**Comment by LagHD** [comment]
Thx
