### ISSUE TITLE
ItemTransaction is break...

### ISSUE THREAD

**Issue by Iktaniyalol** [CortexPE/TeaSpoon#233]
## Issue Description
No plugins, only TeaSpoon 162. When I drop or craft item, its canceled

## Steps to Reproduce
1. Try to drop item in survival or craft

**Comment by CortexPE** [comment]
This is a known glitch.
I tried reproducing it but I can't...
I've tried "NOT" overwriting InventoryTransactionPacket but it still occurs...

**Comment by KielKing** [comment]
@CortexPE go to my server and you'll see this issue, it spams the console..

**Comment by Iktaniyalol** [comment]
@CortexPE But on older versions this was not ... Maybe it's because of the kernel update, but how do I then open the server if the players can not even craft and drop things?

**Comment by KielKing** [comment]
@Iktaniyalol this issue occurs for me 1 month ago..

**Comment by LagHD** [comment]
Disable enchanting tables and anvils in the config

**Comment by MasterOfTheRealm** [comment]
break something to fix something... the classics
