### ISSUE TITLE
Use PMMP Releases instead of Dev-Builds

### ISSUE THREAD

**Issue by CortexPE** [CortexPE/TeaSpoon#234]
# Wait for a new release then implement this.

 - Less problems when it comes to incompatibility & stability
 - Less pressure on updating
 - <More advantages that weren't listed> lol

**Comment by 95CivicSi** [comment]
This should be much easier now with the new PocketMine-MP release schedule.  In case you haven't seen it, it can be found on the PocketMine-MP forums under the News Section.

**Comment by CortexPE** [comment]
Need to kindof modify my pocketmine version checks... as it was based on dev builds and will now be based on releases

**Comment by CortexPE** [comment]
tfw github didnt close it ffs
