### ISSUE TITLE
Crafting isn't working when installed for latest pmmp v1.2.13

### ISSUE THREAD

**Issue by CaptainDuck** [CortexPE/TeaSpoon#235]
## Issue Description

Crafting isn't working when installed for latest pmmp v1.2.13
I think this is already known by you (Cortex) but I just wanna make sure you know :P

## Steps to Reproduce

1. Install TeaSpoon to your server with pmmp's latest phar for v1.2.13
2. ...
3. ...

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# https://transfer.sh/4pHHo/TeaSpoon.txt
```

**Comment by LagHD** [comment]
Ye he knows, for now u should disable anvils and etables in teaspoon config which should fix it for now

**Comment by CaptainDuck** [comment]
Okay, thanks!
