### ISSUE TITLE
Spawner (Question)

### ISSUE THREAD

**Issue by SpecialistNinja** [CortexPE/TeaSpoon#238]
Sorry if i open the issue again but i'm curious if there is a way to fix?

Do i have to wait for PMMP to fix it or u gonna find a way to fix it?

**Comment by CortexPE** [comment]
I'd say just wait for PMMP to fix it.

**Comment by MasterOfTheRealm** [comment]
And use Discord for questions! https://discord.gg/9SJvvFS
