### ISSUE TITLE
Pearl cooldown

### ISSUE THREAD

**Issue by isoz** [CortexPE/TeaSpoon#245]
Ender pearl cooldown doesn't seem to be working, I'm on build dev-169, This server is running PocketMine-MP 1.7dev for Minecraft: PE [REDACTED] (protocol version 3.0.0-ALPHA11)

**Comment by IonicSyz1823** [comment]
@isoz Ye it doesn't work on the latest one too

**Comment by CortexPE** [comment]
EnderPearls are handled by PMMP
