### ISSUE TITLE
Nether bug

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [CortexPE/TeaSpoon#247]
## Issue Description

A short description about the issue
If you die in nether , you cant move, everything is still red, like nether, but u can use /home commands etc... is weird
## Steps to Reproduce

1. ... Go in nether
2. ... Die
3. ... Results

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by CortexPE** [comment]
known bug .-.
