### ISSUE TITLE
Dupe glitch 

### ISSUE THREAD

**Issue by Shelly7w7** [CortexPE/TeaSpoon#257]
When we place a hopper on a chest and when we put something in hopper and take it out very fast, it again appears in the hopper

**Comment by TheAz928** [comment]
probably because it's checked every 8 ticks and there is no InventoryAction made for hopper

**Comment by LagHD** [comment]
Hey least It's just a visual glitch ._. Lol

**Comment by CortexPE** [comment]
yeah maybe its just client-side artifacts lmao

not actually duping the item server-side
