### ISSUE TITLE
Cow Glitch

### ISSUE THREAD

**Issue by Shelly7w7** [CortexPE/TeaSpoon#259]
When a cow is spawned, it doesn't gets killed by lava nor it moves in lava.

**Comment by TheAz928** [comment]
pmmp bounding box bug or cortex forgot to do bounding boxes for entities

**Comment by CortexPE** [comment]
probably caused by [this](https://github.com/CortexPE/TeaSpoon/blob/master/src/CortexPE/entity/mob/Cow.php#L46) because the height is 0 🤔
