### ISSUE TITLE
Anvil Error

### ISSUE THREAD

**Issue by IonicSyz1823** [CortexPE/TeaSpoon#260]
26.05 20:01:18 [Server] Server thread/CRITICAL InvalidArgumentException: "Block meta value 36 is out of bounds" (EXCEPTION) in "src/pocketmine/block/BlockFactory" at line 391
26.05 20:01:18 [Server] Server thread/DEBUG #0 src/pocketmine/item/Anvil(36): pocketmine\block\BlockFactory::get(integer 145, integer 36)
26.05 20:01:18 [Server] Server thread/DEBUG #1 src/pocketmine/item/Item(641): pocketmine\item\Anvil->getBlock()
26.05 20:01:18 [Server] Server thread/DEBUG #2 src/pocketmine/level/Level(1818): pocketmine\item\Item->canBePlaced()
26.05 20:01:18 [Server] Server thread/DEBUG #3 src/pocketmine/Player(2371): pocketmine\level\Level->useItemOn(pocketmine\math\Vector3 object, pocketmine\item\Anvil object, integer 5, pocketmine\math\Vector3 object, pocketmine\Player object, boolean 1)
26.05 20:01:18 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(132): pocketmine\Player->handleInventoryTransaction(CortexPE\network\InventoryTransactionPacket object)
26.05 20:01:18 [Server] Server thread/DEBUG #5 TeaSpoon_dev-186.phar/src/CortexPE/network/InventoryTransactionPacket(155): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(CortexPE\network\InventoryTransactionPacket object)
26.05 20:01:18 [Server] Server thread/DEBUG #6 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): CortexPE\network\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
26.05 20:01:18 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(CortexPE\network\InventoryTransactionPacket object)
26.05 20:01:18 [Server] Server thread/DEBUG #8 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
26.05 20:01:18 [Server] Server thread/DEBUG #9 src/pocketmine/Player(3038): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
26.05 20:01:18 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(153): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
26.05 20:01:18 [Server] Server thread/DEBUG #11 vendor/pocketmine/raklib/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 99.127.25.46 53524, raklib\protocol\EncapsulatedPacket object, integer 0)
26.05 20:01:18 [Server] Server thread/DEBUG #12 src/pocketmine/network/mcpe/RakLibInterface(96): raklib\server\ServerHandler->handlePacket()
26.05 20:01:18 [Server] Server thread/DEBUG #13 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
26.05 20:01:18 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2495): pocketmine\network\Network->processInterfaces()
26.05 20:01:18 [Server] Server thread/DEBUG #15 src/pocketmine/Server(2243): pocketmine\Server->tick()
26.05 20:01:18 [Server] Server thread/DEBUG #16 src/pocketmine/Server(2119): pocketmine\Server->tickProcessor()
26.05 20:01:18 [Server] Server thread/DEBUG #17 src/pocketmine/Server(1701): pocketmine\Server->start()
26.05 20:01:18 [Server] Server thread/DEBUG #18 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
26.05 20:01:18 [Server] Server thread/DEBUG #19 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)

**Comment by TheAz928** [comment]
probably you did /give blah anvil:36 or somehow the player has an anvil item containing meta 36
