### ISSUE TITLE
Slappers

### ISSUE THREAD

**Issue by servantthought** [CortexPE/TeaSpoon#261]
## Issue Description
Console said I need to remove slapper plugin for teaspoon to work... is there a fix?

A short description about the issue

## Steps to Reproduce

1. ...
2. ...
3. ...

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by CortexPE** [comment]
can you give us the whole error?

**Comment by CortexPE** [comment]
no response within 3 days .-.

**Comment by servantthought** [comment]
Sorry... I  was getting spammed by another plugin and didnt see your response
