### ISSUE TITLE
crash with build PMMPdev #1105 to PMMPdev #1114 

### ISSUE THREAD

**Issue by teracube** [CortexPE/TeaSpoon#271]
## Issue Description

Crash server on start using : 
PMMPdev #1114 
TeaSpoon_dev-198.phar

thanks

## Steps to Reproduce

1. ...PMMPdev #1114 
2. ...TeaSpoon_dev-198.phar
3. ...start server
4. ... see crashdump

## Crashdump, Backtrace or Other Files

```text
# Paste your crashdump here (if theres any)
```
ocketMine-MP Crash Dump Thu Jun 7 11:04:24 CEST 2018

Error: Class CortexPE\tile\Tile contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (pocketmine\tile\Tile::readSaveData, pocketmine\tile\Tile::writeSaveData)
File: TeaSpoon_dev-198.phar/src/CortexPE/tile/Tile
Line: 61
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: TeaSpoon v1.0.0

Code:
[52] 		self::registerTile(MobSpawner::class);
[53] 		self::registerTile(ShulkerBox::class);
[54] 		self::registerTile(Hopper::class);
[55] 		self::registerTile(BrewingStand::class);
[56] 
[57] 		if(!Utils::isPhared()){ // beta
[58] 			self::registerTile(Jukebox::class);
[59] 		}
[60] 	}
[61] }
[62] 
[63] 
[64] 
[65] 
[66] 
[67] 
[68] 
[69] 
[70] 
[71] 

Backtrace:

PocketMine-MP version: 1.7dev #1114 [Protocol 261; API 3.0.0-ALPHA12]
Git commit: 5f7c8842555d28ed50c3f3b512078fd806725f5a
uname -a: Linux g1 4.5.0-0.bpo.2-amd64 #1 SMP Debian 4.5.4-1~bpo8+1 (2016-05-13) x86_64
PHP Version: 7.2.4
Zend version: 3.2.0
OS : Linux, linux
```
<!-- Privacy concerns about the TeaSpoonDumps? You can check out the code for yourself ;) As it doesn't collect any sensitive information other than in-depth server information -->
```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by CortexPE** [comment]
teaspoon hasn't updated yet

**Comment by teracube** [comment]
@CortexPE 
ok i will wait ; - )
