### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Emis02** [CortexPE/TeaSpoon#275]
1:07] [Server thread/ERROR]: Error while u
nloading a chunk: Too few arguments to function
 CortexPE\tile\Hopper::saveItems(), 0 passed in
 phar:///root/Altay/plugins/TeaSpoon_dev-198.ph
ar/src/CortexPE/tile/Hopper.php on line 267 and
 exactly 1 expected                            
[09:51:07] [Server thread/CRITICAL]: ArgumentCo
untError: "Too few arguments to function Cortex
PE\tile\Hopper::saveItems(), 0 passed in phar:/
//root/Altay/plugins/TeaSpoon_dev-198.phar/src/
CortexPE/tile/Hopper.php on line 267 and exactl
y 1 expected" (EXCEPTION) in "src/pocketmine/ti
le/ContainerTrait" at line 61

**Comment by CortexPE** [comment]
spoons aren't supported.

**Comment by Emis02** [comment]
I m using pocketmine....
