### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by shdudwns** [CortexPE/TeaSpoon#28]
Install the Ender box, go back to the other world and come back and the Ender box disappears.
The surface wing can fly freely like gamemode 1 by pressing the jump button more than 2 ~ 4 
![screenshot_2017-11-06-20-27-31](https://user-images.githubusercontent.com/26038520/32439448-273ab2e4-c332-11e7-8ab5-00ef3e5cdd11.png)

**Comment by shdudwns** [comment]
@CortexPE

**Comment by NycuRO** [comment]
Pmmp bug, use this plugin for fix: https://github.com/thebigsmileXD/TileFixer

**Comment by shdudwns** [comment]
The wing bug is still the same.

**Comment by shdudwns** [comment]
@NycuRO

**Comment by NycuRO** [comment]
@CortexPE

**Comment by shdudwns** [comment]
@CortexPE

**Comment by shdudwns** [comment]
No. teaspoon bug

**Comment by shdudwns** [comment]
Apart from teaspoon, the wings bug disappears.

**Comment by shdudwns** [comment]
Also, if you leave the item again and give it back, the number will double.

**Comment by NycuRO** [comment]
@CortexPE What do you think?

**Comment by CortexPE** [comment]
A video on how to reproduce?

**Comment by shdudwns** [comment]
https://youtu.be/gdwKY3DPf2E
@NycuRO @CortexPE
