### ISSUE TITLE
Because of this, the pure entity does not work

### ISSUE THREAD

**Issue by shdudwns** [CortexPE/TeaSpoon#29]
ai does not work
It works if you subtract length

@NycuRO @CortexPE

**Comment by CortexPE** [comment]
Wdym subtract length?

**Comment by shdudwns** [comment]
Using Teaspoon, the entity in the mob air plunger is not moving.
@CortexPE

**Comment by CortexPE** [comment]
So should I add an option weather to *NOT* register the vanilla entities?

**Comment by CortexPE** [comment]
Implemented on latest commit

**Comment by NycuRO** [comment]
THANKS GOD @CortexPE ! Same i need and i .
