### ISSUE TITLE
Make a railway system

### ISSUE THREAD

**Issue by XuPaperCup** [CortexPE/TeaSpoon#306]
Make railway and minecart work.
Please also make boat work if you can,thank you.
Sorry that I don't follow the TEMPLATE...

**Comment by larryTheCoder** [comment]
Its definitely on its way now.

**Comment by XuPaperCup** [comment]
Can you tell me when it done?

**Comment by larryTheCoder** [comment]
No valid ETA yet, well maybe soon if you wait, or tomorrow if I'm lucky

**Comment by XuPaperCup** [comment]
And also how about the redstone system,is it done?

**Comment by larryTheCoder** [comment]
You could continue this conversation at our discord community http://discord.gg/7y8WM4F
Thanks, my discord username is MrPotato101

**Comment by XuPaperCup** [comment]
Sorry ... because I don't have discord...

**Comment by larryTheCoder** [comment]
Hmm
