### ISSUE TITLE
Yes sure is a good plugin but is product a lots of lags

### ISSUE THREAD

**Issue by georgianYT** [CortexPE/TeaSpoon#310]
And 
If a day I do a plugin like that I will optimize it. Not like you .

**Comment by CortexPE** [comment]
# Yes sure is a good attempt but is product a lots of retardation
And
If a day I write a rant like that I will fix my grammar. Not like you .
<br />
You need to fix like everything your sentences have .(personally I I think you're retarded

<hr />
jk lol go ahead... I dont really give a fuck. this is a public plugin, use it if you want to. nobody is forcing you to. didn't you read the fucking readme? ITS RIGHT THERE. dickhead
