### ISSUE TITLE
Pls update to 4.0.0

### ISSUE THREAD

**Issue by moch09** [CortexPE/TeaSpoon#313]

**Comment by CortexPE** [comment]
we only support stable builds...
not dev builds.

**Comment by aviallon** [comment]
@CortexPE if you want I could try to port it to the new API, even if it's still evolving, it would still spare you some work.

**Comment by CortexPE** [comment]
Yeah, maybe on a `api-4.0.0` branch...

**Comment by CortexPE** [comment]
lemme add u as collaborator

**Comment by aviallon** [comment]
> Yeah, maybe on a `api-4.0.0` branch...

Yeah that's what I was thinking about.
