### ISSUE TITLE
Remove Hopper from Finished & Planned Features!

### ISSUE THREAD

**Issue by BaconOFBurger** [CortexPE/TeaSpoon#320]
Hoppers has been removed and still being checked as "added and working", so please remove it from Finished & Planned Features!

**Comment by CortexPE** [comment]
hOPPerS has been reMoVeD AND STIlL beinG CHEckED as "adDEd AND WorkInG", SO PlEase rEmOvE it frOM fINIsHed & plAnnEd FEaTureS!
