### ISSUE TITLE
Spawner Dupe

### ISSUE THREAD

**Issue by xDanub** [CortexPE/TeaSpoon#340]
Steps to reproduce:
 1. Get two different spawners, double click a spawner in your inventory stacking them.(even though this behaviour isnt meant to happen because of different metas)
 2. Place the stacked spawners into an anvil together, and rename them and accept.
 3. The anvil should toss back the two different spawners(because they are different metas), and the original spawners renamed to what you chose.
Idea to fix:
 1. When players get a spawner with the meta correlating to an entity, rename the spawner to the same name as the entity.
¯\_(ツ)_/¯ 
Temporary fix:
 1. Disable anvils in config.

**Comment by WhyMeDudes4You** [comment]
@CortexPE
