### ISSUE TITLE
11:12:03] [Server thread / CRITICAL]: UnexpectedValueException: "Useless magic number for crafting-grid type was -100, expected -2" (EXCEPTION) in "TeaSpoon (3) .phar / src / CortexPE / network / types / NetworkInventoryAction "at line 124

### ISSUE THREAD

**Issue by DeadOnBushPH** [CortexPE/TeaSpoon#348]

**Comment by teracube** [comment]
duplicate #346

**Comment by DeadOnBushPH** [comment]
Huh?

**Comment by teracube** [comment]
@CortexPE 
thank you very much

https://poggit.pmmp.io/r/47375/TeaSpoon_dev-262.phar
https://github.com/CortexPE/TeaSpoon/commit/254c3d97ee281927ccb71f51a195c7489ade68ae

**Comment by teracube** [comment]
solved with

https://poggit.pmmp.io/r/47375/TeaSpoon_dev-262.phar
https://jenkins.pmmp.io/job/PocketMine-MP/1722/artifact/PocketMine-MP.phar
