### ISSUE TITLE
Mob Spawners aren't working

### ISSUE THREAD

**Issue by CaptainDuck** [CortexPE/TeaSpoon#353]
Also tried on a clean server with no plugins, using PocketMine 3.5.1 from GitHub releases, place a mob spawner, nothing happens, an empty mob spawner.

**Comment by owenraihan** [comment]
Hey Maybe check the Difficulty?

**Comment by CaptainDuck** [comment]
I set the difficulty to 3 (hard) but it still doesn't work :/

**Comment by owenraihan** [comment]
Can I look the Config?

**Comment by CaptainDuck** [comment]
I'm using the default one https://github.com/CortexPE/TeaSpoon/blob/master/resources/config.yml

**Comment by owenraihan** [comment]
what version are u using?

**Comment by CaptainDuck** [comment]
v3.2 of the config and the latest from Poggit

**Comment by owenraihan** [comment]
Build 264?

**Comment by CaptainDuck** [comment]
Yup

**Comment by owenraihan** [comment]
Idk But I never yse the Build 264 Becuz its not workin on my server. How
about u use 262. But to Change a Teaspoon version u need to delete Data and
Phar

**Comment by CaptainDuck** [comment]
Alright, I'll try doing it, thanks for helping me :)

**Comment by owenraihan** [comment]
Aight

**Comment by CortexPE** [comment]
Try the latest version
