### ISSUE TITLE
FEATURE REQUEST: Barriers

### ISSUE THREAD

**Issue by ZandercraftGames** [CortexPE/TeaSpoon#355]
Hey guys! The latest Minecraft update included the addition of barriers. Could you please implement barriers into the game? Invisible bedrock can only do so much.

**Comment by CortexPE** [comment]
Currently impossible to implement... This is due to the world format not supporting the extended block IDs.

**Comment by ZandercraftGames** [comment]
Extended block id's? Does that mean it cannot support it unless pocketmine implements it.

**Comment by ZandercraftGames** [comment]
Or does it mean that the world cannot physically handle it? Also, if hoppers aren't in pocketmine, but you implemented them... What's to stop you from implementing barriers? @CortexPE
