### ISSUE TITLE
Bug : Entities dropped in flowing water over top of ice, are moving slowly.

### ISSUE THREAD

**Issue by ver24436** [CortexPE/TeaSpoon#357]
**Expected result: What were you expecting to happen?**
Entities dropped in flowing water over top of ice, should significantly speed up their movement.

**Actual result: What actually happened?**
The entities dropped in flowing water over top of ice, are moving slowly.

**### Steps to reproduce the issue**

1. Install Pocketmine
2. install TeaSpoon_dev-265.phar
3. Run the Server
4. Create a water channel with ice and add flowing water.
5. Drop items in water channel and notice their movement is slower then expected.

**### OS and versions**

PocketMine-MP version: 3.5.2 [Protocol 313]
Git commit: fc0782df0218fa4b926060e0ee2b37f1a1cc91eb
uname -a: Windows NT D170206 10.0 build 17134 (Windows 10) AMD64
PHP Version: 7.2.11
Zend version: 3.2.0
OS : WINNT, win

**### Plugins**
**Test on a clean server without plugins: is the issue reproducible without any plugins loaded?**

No, the issue is not reproducible without plugins loaded.

**If the issue is **not** reproducible without plugins:**
**- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)**

TeaSpoon 1.0.1 by CortexPE for API(s) 3.5.1

Video > Server with no plugins : https://www.dropbox.com/s/678vvtxe1qc9mjy/Minecraft%20No%20Plugins.mp4?dl=0

Video > Server with Teaspoon v1.01 (TeaSpoon_dev-265) :
https://www.dropbox.com/s/wn0wzno7cmx7gps/Minecraft%20Teaspoon.mp4?dl=0

**Comment by CortexPE** [comment]
Entity motion (for mobs) isn't implemented by TeaSpoon, we're only relying on PMMP physics... So, yeah.

**Comment by ver24436** [comment]
> Entity motion (for mobs) isn't implemented by TeaSpoon, we're only relying on PMMP physics... So, yeah.

Can you explain, why it only happens when I add your plugin?
