### ISSUE TITLE
Spawner bug

### ISSUE THREAD

**Issue by Shelly7w7** [CortexPE/TeaSpoon#370]
Get a spawner, place it, it will come back to your inventory and meta will change to 0 and will glitch the inventory like you can't throw it away.

**Comment by isoz** [comment]
Yea it happens with other tiles as well, any idea what changed? :(
@CortexPE already said he has no intention on updating this anymore but if anyone could give a hint on what to look for I would appreciate it.

**Comment by Matthww** [comment]
I'm not 100% sure but PocketMine does not allow meta values above 15...

**Comment by Matthww** [comment]
https://github.com/pmmp/PocketMine-MP/issues/2763

**Comment by timothytay** [comment]
Yes I also have this issue.

**Comment by CortexPE** [comment]
I have a **paid** plugin to patch this, separately from TeaSpoon...

**About TeaSpoon:** *I will continue on maintaining TeaSpoon when I find the reason to do so, (for example, if I really need to use it for my server, if I get any reasonable benefit or profit from it).*

If you're interested on the automatic MobSpawner patch plugin, contact me on Discord... `@marshall#1015`

It's 100% automatic, no need to run any command or use any item, just drop the plugin to your plugins folder and it'll convert old mob spawner items to a new, working one.

(Yes I posted this reply 1 month after it's posted... :joy: I barely check this repository anymore :/)
