### ISSUE TITLE
Mobs Movement

### ISSUE THREAD

**Issue by AmeerReal** [CortexPE/TeaSpoon#371]
Mobs don't move.. And you can place Mob Spawner even if there was a mob in the placing block

**Comment by DenielWorld** [comment]
TeaSpoon mobs don't have an Ai so they arent supossed to move. Use purentities if you need mobs

**Comment by AmeerReal** [comment]
But PureEntitiesX mobs keep looking to the sky and on the ground for no reason , and they also suffocate themselves by themselves.
