### ISSUE TITLE
Off-hand Crash

### ISSUE THREAD

**Issue by ManiakMCPE** [CortexPE/TeaSpoon#376]
When you place anything in your off-hand it kicks you

08.04 05:03:28 [Server] Server thread/INFO ManiakMCPE[/76.233.198.151:62627] logged out due to Internal server error
08.04 05:03:28 [Server] Server thread/INFO Unloading world "is-0.85926100 1554705094"
08.04 05:03:28 [Server] Server thread/DEBUG #17 (1): require(string phar:///PocketMine-MP.phar/src/pocketmine/PocketMine.php)
08.04 05:03:28 [Server] Server thread/DEBUG #16 src/pocketmine/PocketMine(250): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
08.04 05:03:28 [Server] Server thread/DEBUG #15 src/pocketmine/Server(1765): pocketmine\Server->start()
08.04 05:03:28 [Server] Server thread/DEBUG #14 src/pocketmine/Server(2186): pocketmine\Server->tickProcessor()
08.04 05:03:28 [Server] Server thread/DEBUG #13 src/pocketmine/Server(2328): pocketmine\snooze\SleeperHandler->sleepUntil(double 1554714209.0176)
08.04 05:03:28 [Server] Server thread/DEBUG #12 vendor/pocketmine/snooze/src/SleeperHandler(85): pocketmine\snooze\SleeperHandler->processNotifications()
08.04 05:03:28 [Server] Server thread/DEBUG #11 vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
08.04 05:03:28 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/RakLibInterface(100): pocketmine\network\mcpe\RakLibInterface->process()
08.04 05:03:28 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/RakLibInterface(110): raklib\server\ServerHandler->handlePacket()
08.04 05:03:28 [Server] Server thread/DEBUG #8 vendor/pocketmine/raklib/src/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 76.233.198.151 62627, raklib\protocol\EncapsulatedPacket object, integer 0)
08.04 05:03:28 [Server] Server thread/DEBUG #7 src/pocketmine/network/mcpe/RakLibInterface(170): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
08.04 05:03:28 [Server] Server thread/DEBUG #6 src/pocketmine/Player(3114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
08.04 05:03:28 [Server] Server thread/DEBUG #5 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
08.04 05:03:28 [Server] Server thread/DEBUG #4 src/pocketmine/network/mcpe/protocol/BatchPacket(119): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(CortexPE\network\InventoryTransactionPacket object)
08.04 05:03:28 [Server] Server thread/DEBUG #3 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
08.04 05:03:28 [Server] Server thread/DEBUG #2 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(158): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleInventoryTransaction(CortexPE\network\InventoryTransactionPacket object)
08.04 05:03:28 [Server] Server thread/DEBUG #1 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(149): pocketmine\Player->handleInventoryTransaction(CortexPE\network\InventoryTransactionPacket object)
08.04 05:03:28 [Server] Server thread/DEBUG #0 src/pocketmine/Player(2315): CortexPE\network\types\NetworkInventoryAction->createInventoryAction(pocketmine\Player object)
08.04 05:03:28 [Server] Server thread/CRITICAL InvalidStateException: "Player ManiakMCPE has no open container with window ID 119" (EXCEPTION) in "plugins/TeaSpoon-master/src/CortexPE/network/types/NetworkInventoryAction" at line 179

**Comment by ManiakMCPE** [comment]
so, is it not being fixed?

**Comment by CortexPE** [comment]
how do you even set off-hand?

I just tried it just now and it doesn't even work

**Comment by CortexPE** [comment]
no crashes

**Comment by ManiakMCPE** [comment]
arrows, shift click them or place them in your off-hand and you crash.

**Comment by CortexPE** [comment]
still no errors

I tested off-hand in vanilla MC:Bedrock... by pressing `F` (literally) while holding a totem of undying... it gets passed to off-hand...

But in PM, it simply does nothing. no errors.

**Comment by ManiakMCPE** [comment]
well, it happens to me and every other user of TeaSpoon. i provided the error.

**Comment by ManiakMCPE** [comment]
you're denying it exists but it obviously does.

**Comment by CortexPE** [comment]
Send video of you reproducing it then -.-

**Comment by ManiakMCPE** [comment]
https://www.youtube.com/watch?v=pwhCfy13I9M&feature=youtu.be

**Comment by CortexPE** [comment]
I did exactly that... The result:
![image](https://user-images.githubusercontent.com/17762324/56096398-70aff680-5e9c-11e9-8676-5933514ea018.png)

**Comment by CortexPE** [comment]
lol
![image](https://user-images.githubusercontent.com/17762324/56096404-8c1b0180-5e9c-11e9-8f50-aab90f0536c6.png)
