### ISSUE TITLE
enchant

### ISSUE THREAD

**Issue by antokiller** [CortexPE/TeaSpoon#379]
hi can you add no limit for enchant plz plz plz

**Comment by naja82** [comment]
Some of Enchantments are implemented at PocketMine so for that enchs you should edit PocketMine
But for TeaSpoon...
CortexPE\item\enchantment\Enchantment
You will see some object creations from class Enchant simply change last parameter to a higher number or use PHP_INT_MAX(paranoid option)

**Comment by CortexPE** [comment]
It's to make it more vanilla-like and not too OP... you can bypass the limit by adding enchants with the use of other plugins.

$item->addEnchantment() does not check if the level is exceeding the soft limit

(hard limit is 32767 tho)
