### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Trxgically** [CortexPE/TeaSpoon#385]
PocketMine-MP Crash Dump Sun Apr 14 20:20:31 EDT 2019

Error: Call to undefined method stdClass::isClosed()
File: src/pocketmine/level/Position
Line: 98
Type: Error

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: TeaSpoon v1.1.1

Code:
[89] 		return $this;
[90] 	}
[91] 
[92] 	/**
[93] 	 * Checks if this object has a valid reference to a loaded Level
[94] 	 *
[95] 	 * @return bool
[96] 	 */
[97] 	public function isValid() : bool{
[98] 		if($this->level !== null and $this->level->isClosed()){
[99] 			$this->level = null;
[100] 
[101] 			return false;
[102] 		}
[103] 
[104] 		return $this->level !== null;
[105] 	}
[106] 
[107] 	/**
[108] 	 * Returns a side Vector

Backtrace:
#0 src/pocketmine/entity/Entity(2091): pocketmine\level\Position->isValid()
#1 src/pocketmine/entity/Living(932): pocketmine\entity\Entity->close()
#2 src/pocketmine/entity/Entity(2181): pocketmine\entity\Living->close()
#3 src/pocketmine/level/format/Chunk(139): pocketmine\entity\Entity->__destruct()
#4 src/pocketmine/level/format/io/region/Anvil(128): pocketmine\level\format\Chunk->__construct(integer 14, integer 20, array Array(), array Array(), array Array(), string ................................................................................................................................................................................................................................................................, array Array())
#5 src/pocketmine/level/format/io/region/McRegion(392): pocketmine\level\format\io\region\Anvil->nbtDeserialize(string x...M..P...%..J.4k7AP` d._y.....+....V....A..9wv.|..a...3..H...(.......#,........^...........b.....x.2.X..9.b.|%.:.....9.F..q..w:Ug...I..;k.........J.....,..7...6....x.0./.)
#6 src/pocketmine/level/format/io/BaseLevelProvider(170): pocketmine\level\format\io\region\McRegion->readChunk(integer 14, integer 20)
#7 src/pocketmine/level/Level(2817): pocketmine\level\format\io\BaseLevelProvider->loadChunk(integer 14, integer 20)
#8 src/pocketmine/level/Level(2410): pocketmine\level\Level->loadChunk(integer 14, integer 20, boolean )
#9 src/pocketmine/level/Level(2038): pocketmine\level\Level->getChunk(integer 14, integer 20)
#10 plugins/TeaSpoon_dev-268.phar/src/CortexPE/tile/Beacon(172): pocketmine\level\Level->getCollidingEntities(pocketmine\math\AxisAlignedBB object)
#11 plugins/TeaSpoon_dev-268.phar/src/CortexPE/tile/Beacon(160): CortexPE\tile\Beacon->applyEffects(CortexPE\tile\Beacon object)
#12 src/pocketmine/level/Level(863): CortexPE\tile\Beacon->onUpdate()
#13 src/pocketmine/level/Level(794): pocketmine\level\Level->actuallyDoTick(integer 1840)
#14 src/pocketmine/Server(2425): pocketmine\level\Level->doTick(integer 1840)
#15 src/pocketmine/Server(2556): pocketmine\Server->checkTickUpdates(integer 1840, double 1555287631.9408)
#16 src/pocketmine/Server(2325): pocketmine\Server->tick()
#17 src/pocketmine/Server(2186): pocketmine\Server->tickProcessor()
#18 src/pocketmine/Server(1765): pocketmine\Server->start()
#19 src/pocketmine/PocketMine(250): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /root/pocketminefactions/, string /root/pocketminefactions/plugins/)
#20 (1): require(string phar:///root/pocketminefactions/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.7.1 [Protocol 340]
Git commit: 5c26deb517838f07b990b24888f31639c8521b6d
uname -a: Linux vps211022 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
PHP Version: 7.2.13
Zend version: 3.2.0
OS : Linux, linux

Loaded plugins:
Festival 1.1.1 by Genboy for API(s) 3.0.0
essentialsTP 1.2.2 by  for API(s) 3.0.0
TeaSpoon 1.1.1 by CortexPE for API(s) 3.5.1
Slapper 1.4.2 by jojoe77777 for API(s) 3.1.0
DevTools 1.13.3 by PocketMine Team for API(s) 3.4.0
Rewards 1.0.0 by Wertzui123 for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
AWorldBorder 1.2 by CookieCode for API(s) 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 4.0.0
MultiWorld 1.5.0 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
Broadcaster 1.5 by EvolSoft for API(s) 3.0.0
PearlCooldown 1.0.0 by AppleDevelops and ARTulloss for API(s) 3.0.0
MythicRelics 1 by DownFallPM for API(s) 3.3.1
MysteryBox 1.0.0 by TheAz928 for API(s) 3.0.0
KDR 1.0.0 by JackMD for API(s) 3.0.0
NoTP 1.0.7 by awzaw for API(s) 3.0.0
AutoClearLagg 2.0.0 by Potatoe for API(s) 3.0.0
Repair 1.0.1 by JackMD for API(s) 3.0.0
BasicHUD 1.0.8 by aliuly for API(s) 3.0.0
MOTDShuffle 1.1.7 by TheDeibo for API(s) 3.1.0
AutoInv 0.0.10 by JackNoordhuis for API(s) 3.0.0
MagicWE 0.4.0 by XenialDan for API(s) 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0
MCPEToDiscord 1.4 by Jackthehaxk21 for API(s) 3.0.0
BankNotes 2.0.1 by AndreasHGK for API(s) 3.0.0
QuestPMMP 1.1 by Gamchik for API(s) 3.0.0
StaffChat 1.1.4 by Thunder33345 for API(s) 3.0.0
RulesUI 0.0.1 by ChampOfGamesYT for API(s) 3.7.0
PurePerms 1.4.2 by 64FF00 & ProjectInfinity for API(s) 3.0.0
EnchantUI 0.5 by UnknownOre for API(s) 3.0.0
KOTH 1.0.0-Beta1 by Jackthehack21 for API(s) 3.7.0
CombatLogger 0.0.6 by Jack Noordhuis for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
ChatScrambler 1.0.0 by ArceusMatt for API(s) 3.0.0
LevelUPSystem 1.0.0 by ZayDepths Development for API(s) 3.1.0, 4.0.0
ComplexHealth 1.0.0 by DuooIncc for API(s) 3.7.0
CustomDrops 1 by EmeraldMC for API(s) 3.0.0, 3.2.4
NoTell 1.1.3 by awzaw for API(s) 3.0.0
AlwaysSpawn 2.2.4 by Philip Shilling for API(s) 3.0.0
Duels 1.0.0 by GiantQuartz for API(s) 3.0.0
ByteMe 1.0.0 by FiberglassCivic for API(s) 3.0.0
FactionsPro 1.3.17 by Tethered_ for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPIt22zaWv4JVZrZOV6REPSxZPe5Zx3aaTO1aEytNZ0azWYiEJNYkwRKkZKXTf997L0ARlJ91
PHPmnE3OiSXicd+4DxDQr425zGKef1yJTIUyaYw6zUYexqIx8vr9fmc42O96zUbEVX6aZTJrjH5t
5JsUuhv6udmIhVJ8gS3HPIpYLlmRBGIeJiJgsciXMmAqD44BhBqNQnUcSSWCvZcwc15E0eswwqnp
kmejVquVSZm3UulfiTwGCHPu50CVao2p6RyanPOxi6NbKvOtka1IrEQE41SIM2BIihg09HuHwrAI
WhujgyGwnnEfvv6t8aLNdmaJJA/zTeuUPvY67QPv5YhV/dMpgZ1OS7jOt6H6kUeh5vWFdwe8s3AV
Jou9g25nB5zun041QudbHwWnYXUeoM0bencA09hqwLrsVvFou2gdL4vkas/rHjxA3cePgVB5Vvi5
htq7F2ooW5lYgJBaR8kqjPa8zvB2Yerx0ymRgVh8sAaNJkxysRAZ83pNVn7vtJuMZxnfsCP8u/fy
oUeABfJg7v/zfztyIQ32H6nBc/8dfdnrHnTuV2Iop1M9aTolvTvfJrP8RCiRhbBQPok9o45rIOnc
dcfw8UfX/ZPbuxocjf+XBe7HDZH7X/jnR/xz5LoH65X7D9fl8NR13TfwsWe4etEs+fsfi9cZ/b12
O+5PMBke//FHd0RtB+5r1/3Fddej9wt4fOu631xtp/1JC8p1B/Cxr0G03ZZLstp/SFavuBJn2DbO
5CoMRLbnDdqPl1YpY+fbTPBAr8nb7Z/IGdxODhGw1xl6g4cx3yDY+TaSj0A9vBd1z7uDaep/GEWT
zaSMBE8YITu4F1m7O7wX2ULkD7LjtVkaFYsQQtBE8MtUygQc3crp7A+rKHQss1xcj09bOYSb1ivB
wUmBfjsPYpcRhAcweHKioVB79nBQxRLWyXWojqJwAdH01SsmZz8LP9eUeU+mbB+VUHZNp9gHCqdO
51ueptHmdD4HPGrv9kE1Mjr36WC4370HlUzepwHPTRzyuvdBGhz07hUnJAoFpB+bEzkJfUulw55R
5I2AdCkySHrAJjv9eyEHd0Hs3wWx39/fgah7IOwuhX+F4DTjqga1yQJZzCLBqszLPei1hxrb/l3Y
ujfoL7HlSLeePbhrtjfcv2c2LH4f0juZGTDDO8B4g/27iFA5z0xO4N1Yr1VaB1Jr3wHBDvroliiV
PANPAXLTltiszSvAyhT4TB4mZ3KxsEaZ8HJnlvnwiHLJ6TSszfYw0crEL0WYbaPX5+ey1QjMY182
/v5bsyGeP/3+fckx0KC5/xgmKxmtRAw5IMwPkwCY9/NG2Q9tpUeCNl8GAskeHkD7NJ/mmciLLGF/
yJeh+gYGHLSp4zf86sFX/OxQU+vrr/GhSw/sa3aMq0excM5wrtEqW3LFOFthpg2amItMJL5AOXCG
4QTEQAsZIfUMJPzeL6H+tyEIIwt27JuOFj4M6CGFZRn6bF4kpEK2TezZiKb9ikOHhr9wvke8QTRD
vOw/Dg9ZApUO40nA7B4sEEp1vCQQpYimeQ2Cno+y8tptLSGv7W3HGvrnPFJCD+qYvt/oqVtO6d2i
gV0qNYD+ViVee7+cPrCU4rWHpfzeETTUgYI8gf0IOgHD/O1LLfWllvpSS32ppb7UUl9qqS+11Jda
6kst9aWW+reopZqNhUhExiOsShKOrzoaNTBAzgxEU70SaXQhUHnYXIRR0Bh5g/5+sxEq9BGNEeXd
UPtkMpc+lBCjLphfYxFibdT3O/uBmPW9wbA7nLcHs4OD9qzTGw6H86633z3wh/2ON9sPAHbGr6Jw
BnPartdx29BSGOLOwqS4ZqtUdTxI7Tus53p9t+30Bg4xAoXJi37beT8rkrxgl+dj9gFqnnMOC6HL
vPao1xv1O+z95Bj8MFjN9XD/434Pi7VlCsAHELu9Ljx+EklArGrk0PtRqhI7NNBDRA/bSlChCF9D
rhquauLcNjUblRA91yMh8gKK0kxhYfCdSGZygyrhaYgNXUgD2vgsEg6rFwgCUwXhBiIF8nAO9Ck5
h0THaog5FZ0Lgjadlti12WIFC/aNSr64nHy4eHd2Ak1rMYPKAmld5nmqwMRAYcti5voybmlArS0X
WH0rhVk6qHoythitNdeZ7bidGrPPxKSNESqHOv57GUU2tnV5xYJVqt+rqzLw1LTVh1FPZKQKZHUt
XU6O3k3ej2/VUTnHvd58QnYuI4iwIrO4KVvqzPR2dNH4Wf4sxQD/1djxnq4XpRE/2eYqilolD8Dg
iVhNIElTFofbph19dd1uncfKpzHQcVxjtPd0Rkv806lFySN0Z/FaUdbawgBm34k1zwKb17Klzmqb
HJTF6QeR5Z+K0Ot0n8uVVBCnU0PEkzVbwWoZUC3k9hQCsYw3R+O3FsNWo81zH+LPjgXLRMzg/3Mx
bMCBR9EUAMzptEbNg77l6IPMouCVzILaiqw177jIXQ8jr0JxjPuFu1w16dMznx3z2TWfPfPZN5/7
8Nn7HGlUlEDRYNH/OBtAYZwXUR7STEsUVmNdEP1diz7+JPzl+BxWBxr/j+F1eHX8VzoxsSlyVVyF
8P0KyvzwSj2XBcRI3BqJAy5tQn+vvVu0tyxAIJRXGYDyucprBmK37oilLpTTlYwugfrn4thCDHVU
jYpH+LP1eu0KoAihu/kV8jcWPIvAdqJAru0QW29/wJkdQc0oTrBckqmiPWOgoYgiqZ5N1T+JRKbL
MAp9yJZqxO08PsrSN/ky9N8JgGa77lpzjeU6uyeA5jUUm+PzGnfdpycWNmbwYStIkHSB8zhu0AI2
r+R1jZdt4wPKmyzF0aeDzvDZFqXGPJPX0ykkP+IxLHx/8s6iHZ8eIPpP3L86P3kukjW06RQQ05/H
kPyDrGXV9LhL9KBONF9/4uvnopmATaeJzNMnh3lNEMbBIpfHESyjM75Y2IGw1m6z17mpk7HMeS6f
LbzXcD+ZRUPUJIPpf5m06gxRApfyMKvlb9Swq0rvX2F/GveTedVgWoYDDF5chf6b9yd25Cqbdhkc
7thqFBbRs5W5Gtp0uiyCpxtrJH6G0JJJgGVtljjllkyeCdGKKRq2tlyie7yYnFwui/k8ErZ/tFp3
q8jBDQd5IsKZfK6yy0L9mEKyXJ9vk9XOysQWm/Y22uktjvIHCZngsgifLRj/DECTEuh0CuhkmKwg
79wS9XDQ4ovQ/3Bqa8S01Dnq7XoZSARCHp3wZJcZ5+hs/OZoYPJp8zgsH5+sLE3VYxV1fjw+nciT
UPkgHZu5WvtOpX9TY/lSLPn1Vcd7Tg8D1a/Gj8Q8vix4xROwoFyomhcp23Zjwo6fPIIFK7h68933
v4sTu6i8L0RsoeMLK0OS9fUx7P25ECofn5/bwbxq23ENO1uBPPaX4dWzBbxIXL/KQkhoCf90+gt+
PIqJy5zP58dLntvbStu2Xf/W2/VvePom63a7vf5z8WLDnE63pFhfnxABDNATKdTYOP0KHMbyIhLq
vb03Ubbc8JI7peuSx+nFHPQp1F8mNRkMPqMit6BCbEdSHr/qxkUmxiKL7VVXtT2wVbjfe/263Wb/
ycaZxDcfb5N5mIT5s4XzjxoBVF4lRdbXpyRpONdotIKDG06Jv+RJXtNp1VbX6k7l/T6BELVOLrJn
S0griHjsxRDxeI1+fzF5Yxc5+HijynFeiZx7dwQEfzcgDD43ICARj+fgWMYznut3ahYntebdlbZ/
kxf2z85HfCIoIoKwBq2R9yCXr2UW13c4y5a6trq7mckdG/Sdz+BrC3E6NURsvzxKYeAYL/2Mx4C5
prFa+0ObO5kvCnXO8/yfEcJrpDy9NiAaY6QR2KYX9+/Hl7gREVts19sfYPuvfAP05kvFzMYWHR3d
LQE+c9O2RtHvWogpJAtvBI/yZX0lWu0PMHhSSEjWff+5PEoJj1ZcRcbO46NZLFQu45NMpnYEtFvv
2aA7jfFdOeS5t27KdyABeiKPW8DAVUXK4xX3g5yIKKpvG2HDbobW/ZdsHAHmZ9g6itZ8oy5TXts+
tlvrJUJnN/0c465uyi7hIwqTxXOxSZvFqTJQoUglihRSNJ3ubq7eVc6dFKL+IpOeH1hY34WQGfy5
4Fn+6V5mzCGMR3GTSRl7EAWIAPPxkNbydZjnIiN12TRhTbfJxbm9HWIaHuDsdTgT2QKP3xyHq9B/
vpcagufLCb8CRUWbV2HCsw1UcURS+fmwrl6b8zWQ89qx22rdjd/e7kaPgDQrE8HHz2OM8nRT4hwl
eQirIEb0FcMWURDP9cPvKQx2Kj0LX70s8Lzb6oLfF8arfPwmo3Xh/iRWoSzU+NQp2xt3lAy6FLTI
/tyCQVeAeMaHQyohwOqJPveWs1bEBp0sc1Nw3iLDg5eA5cV4+8SOJRRMC4aXTabZNHlxyXN2lOrD
Sd6o18bDSacnEzqchAMiniwKvhCHAjwNPMcyDw5/EpkMfVbKAts1XgfVdk93KrP80DvwOm1sXMDg
WAbikJ5ifu2kEd8Ag4ddaiGP5uBJLkGQDr0+ta+XID0nChXAwmetYeeXQmSbQ5lYTRkkaqYFv7op
rO81JNOHX9O/acKTRBaJLwxmh/vLUOi7NMpMnEvIwJwtrXI+x1YQd+DLbPucrlIzPgjn89Avonyj
qdPH23KZOUrkOfgBdUiCpSOYJK+/Ajb+UfvvbY8SIrAG4jWjw5PT10fvzybYihuTjuIrYbCuQrF2
AhAJB24Oh9h0PZPXDi4RM0SLkydhDN651hbLWdmAZ822G9DuJo7QfhiuYOaT6RTAC166QQtiIBtW
s0OwKDZZCiVYySzjmWDgfJhMwPxysGbmo9RzNhMsTPyowDtBAP6G5SKsSxnDTLxhdAOm4nPRZBL9
mkKQbAa+9optZJEZWHg1CXQWzkPCAOrCi1HRBgH/INZbcK1AzDkoTLG1TL7KGZ734RlDEUPeHfp4
+BYppGtOxPd6KRJWpIuM4xlnd5qghWtgo2nC2IsPS3K4eO9JgUtheBdMn6EEGWQ8URHPgSjqJlIj
CWiAVfgmcpJXAD7HFwxq8SAiCcYIWVtjuSpH+poRdqhlkeNLYsfcQBuxaUMfM2V0IyaYNoiyoyiS
a4aLhw50ak/DViFnf8b1g2NoIZUvH0YM/SZNvVzCTI52oCSQZBBpYXADihUK1AxOFkRNLEKRZC6+
KQRS9ThA2gwIsxCc0qotIeHLdlxiDEwCpI7kzjbM6ArHm0W+7bak8eIDJEdgcqA4HuBFNKX1i6Ti
6V8giSvwrrjQGWh1JlAqIH3xS8Hp2t4iXMHYFY8KwfYMUjw6j9A1RnAvAh2aA3rFCnwE3YT7hyKe
4dHcOTtSm8SfcHUFlpVdgaG6NOA9qIPWTskpDltmUFQWYB4wXDUZnf1gxnnAgmuCLGKQncIgSLKB
MIJtcZGAidKvbGgtkf0AT2DGmbyG1Q7Z8AZZoqWRbIlD2RqC3s5xMdAtPTD6Jgvzr/DyYkbTAoH+
l2xyZzLbAx5A4axDYiE2HMPpiEDtLgZO1pcVSYLqDKryk9FhXuViSWq+szhcLMFbZFwtm/bqNpaJ
EsmyIs11qxYYCiYG2gxfpFwwOBATLEO94vhKhgGQfTsFaCNocxIEDdblWoaGdxD0oK2lQdiCsJBt
9Kr/LpIzsB5MJZhuh4UWhzk6j1gs+AzyPWDxUou6TcINFcKm6RPU2jokyZNFgVdYOxpQaWT6DMo8
BBLB5Qk8ToFg5pkQJUpt5KCtgpbnQoKiJPoBtApEtCAyHSJtxNrIBWAnH58v8RbOvz0HmHndRz9G
58+jHyrglEgw/nlLkgGnGLgPTCfAsZYEIdaSKq/d6RnCyAl8oFVh6FNfPQOFtC6IJPQYzC8guiUQ
3Zi4Fn5B3l1qkvWK1Bd1zWhx7UN+oSqOtOO6mJyO2OTN20t29vb87QSc9/js7eklG5++Y5C9fn/6
rslgEJtcwKhT9uHNxdkpG7+7OD69vHR3XUBNHp3+vhEHZNyhpIiPjlghg3R3pJTG1tl6IHuINQH5
FhrigCsU2s0SKEhmgU9w0GBNyO9dxqaNDNJGjLAJDjPICLIGAq63cuQ6IhGOC4whmEjQBPfmaLQF
U2OA2lLhY76hJYvkar3quVsewLxEqipWu23Dq3p5O0mG867hfMGzGawMx5dRpHNjckC3S5eWGpJj
ZjEzC3x3zBO6WlSjBDK/AmwQr5DeboSlGerwqu9TEYK4WoIuu9A+Xxs8pCeyiIItLSEEkXXCKvqV
BpwS+cDofrtteAVsr8lZ3AiSZDoawpa3eSbjMtjq2WaEY5umrWHkxmjyhm2wW0yqZh2XZUaKKssk
bciUhhwUcarTN50jMtPhYEeprxMcZCYQ7URmyQE8QZjHy+q3CBiCNgQ+wLACI1OqEOgY8iVobVGm
s+i0EFtFVbNUpM4RTNbqampw6J1ywvrMx0uFqqT9mKfYGsZFDDEW31+ysgJBRTJdU2kqKrniejGi
pBVz08Ygm08NRYTQwTS7gKDb22rsROquXZvG3Ai9noavB5dLSMMyA23OKHNwfKj9xJa3EyCFchVI
H1F6QJ1OMDSUlGPRw/QczWHFHUwz8tT8lJhxcJXtogDxuFYJ935Q99nhNElEjgobmRABqdlSRjrF
nPEcalpM9YlkhfdAmQky5Nt0aWV6dWiZiW2yqcPbC1tLZRe61QxPdyaLJnM8S4GkPELs5CUxJgSQ
167yWP1rBwXmw8Q5FkuU6ONkaDRkuewN5IJgS4eU3LHj8fsmzAUaZrC+1mEAZk+5gvaeW/gOwR+x
QZl2Vxm5IulYY112FICjWvJo3oJaVZcJgQAbNqgAKf2EBRqYtRCrsGcBs0uR02v0aphi8qipnSai
/hAmUK8Ba+B9BPkyzKTfj5NxmYdXxSeWGTgJ7ysgzCJNUsc87xQ+52ZBqvCT2KoaM/ZSw3hFqcym
IKPXlmNF3d5BR0966bKxmRPxbEETuKmCjZkQxnnGF8gdqAvYUmlEyQyWtjEQj36AZ6jC4yjEbRWq
1fFeoVA5O5+8J0oVsIRsz4qc4d4AablCp+sOt3RDcV44OGtE1OICCMSsWIzKWuZb5mENYzI5rFqp
v6xYlS7mRVnJ4jRjKB4C035LQzteSqhR0TjLEkaURSo5t4DnnCm+Kp0obsmUm0nYV613DjEdPIHg
eeljgFK9UV6mzFRugQlRuqJSyNAofUmkj68RaC7I8ZxvQIZoLLFclRUsun/jM8lvOWWfRqkqb1Fu
L9nbFRPab9AGoK/K650aGmu0XShT6vu4p639gpnj6DkjlkJCsQojnfbWLBjPFICbNgBpbVEiBAzj
WspxPXXaJmnB4KHzIRIcbnVhh0mCtgKttW8TzXbpsHTIxLujFr49D3zILYiarAMd3m0dIvfdl9qj
KWET4mnZIWzc3zGbl0yAJ9cYUZFaZrRNVe1fBWV0QevWiTO9w9HQDSCryNQBxDhHozJZytRUKAnq
INoNxM1yVG2D8Nb9Nl0yH8WyQAcx15HO+Au0S8MeigbJpI0QsHL8TqEZJr+jQG1NJitKhC68Z0ID
m4k5Lm/ae6TYuiyXE60g2pKshXzNPiLasg9ujvFdUlN9pxuwbXWwQ2X7djJ5BpAC2sSiVQ3ElpON
vjU1XXIVuC3hFPqau+V6fYzmWoO4vWbta709IWSzSKJtoX9DeYoMlw2YJcSBmBnumNnGKVMHmlNj
HeA5YKwv2AIKQFWJp9oq2krIvSki4/nWPKQKEbxwIYxuUpkWUbmyzQPGUBpj/O0Q8dEScVLjInEZ
otcbsTJnp4Wp98ZGZjHiVh7Vq7pZB1+jLnyHud1kCSqxobk7+HtVO01b11VvTpeQ5s6lpRDwWI5+
w7IduZSoGCLFTeM4dUNJFCcy2cRYb8H6yHFv1FcV6VhEmn5W9RML5P75YpFB5a536bbboJiV4m8u
Xe3yR/TBAr44ucAL9o4JKDquorNYC53Uc1g5a8KoiPCKAWpzrY16CONbyWvL1Mq5IVTQp+43tgQZ
ROKYOGjnptQubdFBup+gmVhbZk1wW+mSN6EZxIDBP9+mfyn9+Bek+A46oASDq+4tg7TegOO1LTjz
js8K3gWkupAnkBMrfYUBSJrX/SWOG5rWvNqqziFMbOOeie4IFMeXSRhqFv0lIqS9RTOp3Ed2KwSm
x8ZQSvP+/MF4ba1dvSqsLZtyjz0PcyPPcnNmaRrJYWB1ZRJ24zBwrxtqooAy1nC+BQRlDzCi35yg
Ayp3LLSLA3jGQ5ZZAo9CiHZGTKfXHM+5mCdMqIBGo6tRqTTdB3aLW2cj9jfKhCDKNWkv7e8IlCqd
KuWw3+gQG5iVZvirZbRbUb43o22I2wIWJUcURxUl5lTl4hVHoNVkGjb5Gi/RoL8yfMeGQUEHrwrj
iL0+O5qMOt8Mmv2Da6/Zve42O9943wSQEWgXu4dXMnz0rYfDtvbE+qnXf6lTSP3yxN4k0CscQwvI
2OzhURpHm3CgNX/D9G+BFFnpk8vKKNu+FSGPA3AgUvn0WkuVAnPKVzZgCzpXfvGaXA2hovE1IHTi
2LR8tFocSlzdartRplRXi2twfMoUlf4V3Z2mAgokMgsh69/o/Qcah/wCKVDy6Cii14zmkuBDLpJt
fXWj2RDXuUgUvVof/dqg23XWz2HgKrafwQQSpSK7KfXrU9QvQJLo1n5UQ/+kx/Z55uMvEdkt+BIu
CXhWa8s2aS7p0GeXjlf75jcfqxFFViPlZ2XOKezTMZN5GNEd22rAPK/92MciqD3Ftc4lxCp9ZgWZ
gvQNyKuNvxyf2Y9k+IH+6ZIO0RvP9KtHe1S8AfnQT4yYb6yPh8c7+JKDOfj6v9/utQfw9Q9vcT9u
OBe805t3hr3BnA/63kG77c1E96DtHwy5aHOfz0V3OGB/IE0keU0e4yVJtGMui1dx6yNlJfSrNvqn
VvSPnUgVXtdUa3YR6QdRPHeAP/SC99vmZsunpvZlLGvyU4RN1axJmd8EwSO84WJGx3IMgXitJpdX
IoF8p6azDaeX4R1zw/1TmOoTbX16JCmG1fjffvs/EZ+ypA==
===END CRASH DUMP===

**Comment by AndreasHGK** [comment]
Disable the mob flag on all of your areas in Festival, and it shouldn't crash anymore

**Comment by naja82** [comment]
To many plugins make a core

**Comment by AndreasHGK** [comment]
What does that have to do with this crash?

**Comment by Trxgically** [comment]
> To many plugins make a core

> What does that have to do with this crash?

^

Ok i'll test it out thanks

**Comment by CortexPE** [comment]
wtf why is the level an invalid class.

Please provide steps to reproduce, otherwise we won't know how to test this.

**Comment by Trxgically** [comment]
I'll try to record the steps
