### ISSUE TITLE
no mobs

### ISSUE THREAD

**Issue by teracube** [CortexPE/TeaSpoon#42]
hi,

no mobs on my server

is it a plugin  issue or configuration (config.yml) needed ?
no change on config.yml
thanks
sorry for my bad english

PocketMine-MP 1.7dev-406 latest build
TeaSpoon 1.0.0 latest build

Others plugins  :
 AllSigns 1.0.5; AlwaysSpawn 2.2.3-3; ChatToDiscord 1.1.0; VoteReward 3.0.2-3; essentialsTP 1.2.0-2; Worlds 1.0.12; TeaSpoon 1.0.0; Slapper 1.3.7; iProtector 3.1.0-5; BadWordBlocker 1.2.0; xyz 1.0.4; CustomAlerts 1.7.2-2; PurePerms 1.4.1-2; PiggyCustomEnchants 1.0.6; EconomyAPI 5.7.1-3; BanItem 2.3.2-2.alpha8; EconomyShop 2.0.8-5; FactionsPro 1.4.5-8; PureChat 1.4.10-3

**Comment by CortexPE** [comment]
You can add mobs (with AI and Auto-Spawning) with a plugin called PureEntitiesX...
just disable "registerMobs" on config.yml by setting it to false

**Comment by teracube** [comment]
@CortexPE
according TeaSpoon file i thought thaï this plugin included entities and mobs no ? 
thanks
sorry for my vas english

**Comment by teracube** [comment]
@CortexPE 
thanks for this great plugin
is entities and mobs are finished or planned ?
