### ISSUE TITLE
Crafting Table

### ISSUE THREAD

**Issue by xSoapers** [CortexPE/TeaSpoon#461]
when i crafting, the item back  to normal

**Comment by DenielWorld** [comment]
Not TeaSpoon related

**Comment by xSoapers** [comment]
When i am not use TeaSpoon can crafting a chest and more block :/

**Comment by note3crafter** [comment]
Yes i have this Proplem :/ Teaspoon need an Update

**Comment by teracube** [comment]
https://twitter.com/dktapps/status/1203695593798979584

@CortexPE stopped maintening it ...

**Comment by NycuRO** [comment]
#467
