### ISSUE TITLE
Sponges copied from MY PLUGIN without even mentioning me

### ISSUE THREAD

**Issue by Invy55** [CortexPE/TeaSpoon#491]
I recently created a [plugin that makes sponges works](https://poggit.pmmp.io/p/Sponges/1.0.0) and now you picked it up removed the license and putted in this "plugin". Please go and read the 4th point of the [apache 2.0 license](https://choosealicense.com/licenses/apache-2.0/):

```
(a) You must give any other recipients of the Work or
          Derivative Works a copy of this License;
```
After this I will change the license because copying without changing anything and without mentioning the author but saying that **you are the author while you aren't** isn't so nice.
Bye, thank you for  ̷y̷o̷u̷r̷  **my** job.

**Comment by DenielWorld** [comment]
How are the authors supposed to know whether the code in PR was copied or not. They don't go around looking through all plugins for the exact same code. You have the wrong understanding of reality.

**Comment by Invy55** [comment]
Ok, so explain me. (It's not me but you have completely copied it without changing anything. The license was clear)

**Comment by CortexPE** [comment]
your repository was uploaded today (17 hours ago, at 2/20/2020), and the PR
was 12 days ago. How is that believable?

we have no exact knowledge of who did what. I personally just give credit
from who I took it from, and I don't maintain this plugin anymore. I didn't
do the sponge PR.

why are you deprecating me as if you're the one who made this entire thing?
this isn't YouTube with a broken copyright system lmao

I didn't even review nor merge the PR. And like I said, **I don't maintain
this anymore**

if you can prove that you were the original creator of it, a maintainer
could include credit on the README file and the source code... I can't
guarantee that any of us have time to do that though.

**Comment by Invy55** [comment]
Yes, because I changed license so I've recreated the github repo... Later I will try to prove me

**Comment by Invy55** [comment]
Ok, so some days ago it was on Poggit but I removed it becouse of this so now I don't know were to start... let me think something like github cache or google's

**Comment by Invy55** [comment]
Yep founded [HERE](http://webcache.googleusercontent.com/search?sxsrf=ALeKk00MVZOLBq34v2g825GLbMMcLZsODw%3A1582211193446&ei=eaBOXtPlGsTrrgTO9JyoBw&q=cache%3Ahttps%3A%2F%2Fgithub.com%2FInvy55%2FSponges&oq=cache%3Ahttps%3A%2F%2Fgithub.com%2FInvy55%2FSponges&gs_l=psy-ab.3...10900.10900..11711...0.0..0.78.146.2......0....2j1..gws-wiz.........23%3A10-80g0g68j24%3A10-1g0g1.UQgRuFSev70&ved=0ahUKEwiThpSBtODnAhXEtYsKHU46B3UQ4dUDCAw&uact=5)

Or if you want just go on google and tipy `cache:https://github.com/Invy55/Sponges`

**Comment by Invy55** [comment]
Using the same method but on poggit page for just 2 seconds it shows up this screen then go to an error because I deleted it:
![image](https://user-images.githubusercontent.com/38048104/74948521-b6164c00-53fc-11ea-9e34-b2b7f9600aa6.png)
And you can see the release date

**Comment by Invy55** [comment]
Ok do what you want, feel free to stay with that garbage code in your plugin...
