### ISSUE TITLE
whole world is not loading coz beacon effect used!

### ISSUE THREAD

**Issue by optimusprime338** [CortexPE/TeaSpoon#57]
![image](https://user-images.githubusercontent.com/27479208/33193823-351259cc-d0f1-11e7-91ed-64b48869844b.png)

**Comment by TheAz928** [comment]
1. Update your tea spoon
2. Delete player data/world
3. Restart

Oh, better way, do not use if you can't use it

**Comment by optimusprime338** [comment]
Bruhh delete world?? And delete players data?? Is that a solution😂😂
