### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Emis02** [CortexPE/TeaSpoon#79]
Please give me this plugin but compatible with alpha 7 you would be very useful. Sorry for my english but I'm italian

**Comment by Emis02** [comment]
It makes me wrong but in alpha 7 you do not have anything like this?

**Comment by Emis02** [comment]
[Server thread/CRITICAL]: Error: "Call
 to undefined method pocketmine\command\SimpleCom
mandMap::unregister()" (EXCEPTION) in "plugins/Te
aSpoon-master/src/CortexPE/commands/CommandManage
r" at line 68

**Comment by SuperKali** [comment]
@CortexPE poor boy, you don't need any plugin, this plugin is only for 1.2.x. but you cant update you server  on 1.2.x?, because your server is outdated!

**Comment by SuperKali** [comment]
@Emis02 please you close this issue because your server is outdated, isn't any sense this issue

**Comment by Emis02** [comment]
Kali did your business, nobody asked you anything. I asked for a favor

**Comment by SuperKali** [comment]
@Emis02 I do not want to repeat the same thing, please close this issue your server is outdated ok?
do not seek help and do you make the plugins!

**Comment by TheNewManu** [comment]
Hahahahaha I die

**Comment by SuperKali** [comment]
GG

**Comment by NycuRO** [comment]
Closed. Cannot reproduce, plugin it's perfect functionaly. Plugin was only for latest versions, thanks. If you want for oldest version, it's your problem.
