### ISSUE TITLE
issue or not : Ender is generated like a normal world

### ISSUE THREAD

**Issue by teracube** [CortexPE/TeaSpoon#89]
## Issue Description

I delete Ender and Nether  then i restarted the server.
Nether is generation is ok , but Ender is generated like a classic world
i paste an extract of pocketmine.yml file
it was ok before regeneration of Ender
How to solve that
thanks

## Steps to Reproduce

1. ... PocketMine-MP version 1.7dev-526� "[REDACTED]" (API 3.0.0-ALPHA10)
2. ....TeaSpoon v1.0.0 =) TeaSpoon_dev-55.phar
3. ...

## Crashdump, Backtrace or Other Files

pocktmine.yml extract

```aliases:
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 ender: []
 faction: []
 lobby: []
 minage: []
 nether: []
 rp: []
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)```

# Paste your crashdump here (if theres any)
```

```text
# Paste the contents of your TeaSpoonDump here ( by running /bugreport ) [can be found at <TeaSpoon Plugin Folder>/dumps/<time>]
```

**Comment by NycuRO** [comment]
You need generate nether using level-type as : 2. (The End or END).

**Comment by teracube** [comment]
@NycuRO 
thanks but before I delete ender world created with TeaSpoon it was Ok
How do you do that "You need generate the end using level-type as : 2. (END),"

**Comment by NycuRO** [comment]
generate world using server.proprietes ,and on level-type add "end"
